/**
 * Clapping Applause Emoji Data
 * Category: gestures
 * Generated by scripts/generate.ts - DO NOT EDIT MANUALLY
 */
import { EmojiData, EmojiCategory } from '../types';

export const Applause_DATA: EmojiData = {
  name: 'applause' as EmojiData['name'],
  label: "Clapping Applause",
  category: 'gestures' as EmojiCategory,
  keywords: ["clap","applause","bravo","hands","cheer","praise"],
  unicode: "👏",
  version: '1.1.0',
  svg: "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 128 128\" width=\"100%\" height=\"100%\" fill=\"none\"><path d=\"M22 96 L46 64 C52 56 62 62 56 70 L42 98 Z\" fill=\"#FFE5D9\" stroke=\"#1E1F24\" stroke-width=\"4\" stroke-linejoin=\"round\"/><path d=\"M106 96 L82 64 C76 56 66 62 72 70 L86 98 Z\" fill=\"#FFE5D9\" stroke=\"#1E1F24\" stroke-width=\"4\" stroke-linejoin=\"round\"/><path d=\"M48 62 L60 48 C66 42 74 48 68 56 L58 68\" fill=\"#FFE5D9\" stroke=\"#1E1F24\" stroke-width=\"3.5\" stroke-linejoin=\"round\"/><path d=\"M80 62 L68 48 C62 42 54 48 60 56 L70 68\" fill=\"#FFE5D9\" stroke=\"#1E1F24\" stroke-width=\"3.5\" stroke-linejoin=\"round\"/><path d=\"M64 24 L66 32 L74 34 L66 36 L64 44 L62 36 L54 34 L62 32 Z\" fill=\"#FFD166\"/><path d=\"M40 38 L42 42 L46 44 L42 46 L40 50 L38 46 L34 44 L38 42 Z\" fill=\"#FF85A1\"/><path d=\"M88 38 L90 42 L94 44 L90 46 L88 50 L86 46 L82 44 L86 42 Z\" fill=\"#FF85A1\"/></svg>",
  viewBox: '0 0 128 128',
};
