/**
 * Cute Avocado Emoji Data
 * Category: food
 * Generated by scripts/generate.ts - DO NOT EDIT MANUALLY
 */
import { EmojiData, EmojiCategory } from '../types';

export const Avocado_DATA: EmojiData = {
  name: 'avocado' as EmojiData['name'],
  label: "Cute Avocado",
  category: 'food' as EmojiCategory,
  keywords: ["avocado","guacamole","fruit","green","healthy","cute"],
  unicode: "🥑",
  version: '1.1.0',
  svg: "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 128 128\" width=\"100%\" height=\"100%\" fill=\"none\"><path d=\"M64 20 C46 20 34 38 34 60 C34 86 44 108 64 108 C84 108 94 86 94 60 C94 38 82 20 64 20 Z\" fill=\"#2D6A4F\" stroke=\"#1E1F24\" stroke-width=\"4.5\" stroke-linejoin=\"round\"/><path d=\"M64 26 C50 26 40 42 40 60 C40 82 48 102 64 102 C80 102 88 82 88 60 C88 42 78 26 64 26 Z\" fill=\"#D8F3DC\"/><circle cx=\"64\" cy=\"74\" r=\"20\" fill=\"#9C6644\" stroke=\"#1E1F24\" stroke-width=\"3.5\"/><ellipse cx=\"54\" cy=\"78\" rx=\"4\" ry=\"2.5\" fill=\"#FFA3BA\" fill-opacity=\"0.9\"/><ellipse cx=\"74\" cy=\"78\" rx=\"4\" ry=\"2.5\" fill=\"#FFA3BA\" fill-opacity=\"0.9\"/><circle cx=\"58\" cy=\"70\" r=\"2.5\" fill=\"#FFFFFF\"/><circle cx=\"70\" cy=\"70\" r=\"2.5\" fill=\"#FFFFFF\"/><path d=\"M61 77 C63 80 65 80 67 77\" stroke=\"#1E1F24\" stroke-width=\"2\" stroke-linecap=\"round\"/></svg>",
  viewBox: '0 0 128 128',
};
