/**
 * Boba Bubble Tea Emoji Data
 * Category: food
 * Generated by scripts/generate.ts - DO NOT EDIT MANUALLY
 */
import { EmojiData, EmojiCategory } from '../types';

export const Boba_DATA: EmojiData = {
  name: 'boba' as EmojiData['name'],
  label: "Boba Bubble Tea",
  category: 'food' as EmojiCategory,
  keywords: ["boba","bubbletea","tea","drink","tapioca","milk","sweet"],
  unicode: "🧋",
  version: '1.1.0',
  svg: "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 128 128\" width=\"100%\" height=\"100%\" fill=\"none\"><path d=\"M72 16 L60 60\" stroke=\"#70D6FF\" stroke-width=\"8\" stroke-linecap=\"round\"/><path d=\"M38 48 C38 36 90 36 90 48 Z\" fill=\"#E8F4F8\" stroke=\"#1E1F24\" stroke-width=\"4\" stroke-linejoin=\"round\"/><path d=\"M40 48 L46 104 C47 110 81 110 82 104 L88 48 Z\" fill=\"#FCEADE\" stroke=\"#1E1F24\" stroke-width=\"4.5\" stroke-linejoin=\"round\"/><path d=\"M43 62 L46 103 C47 108 81 108 82 103 L85 62 Z\" fill=\"#DDB892\"/><ellipse cx=\"48\" cy=\"78\" rx=\"6\" ry=\"4\" fill=\"#FFA3BA\" fill-opacity=\"0.8\"/><ellipse cx=\"80\" cy=\"78\" rx=\"6\" ry=\"4\" fill=\"#FFA3BA\" fill-opacity=\"0.8\"/><circle cx=\"56\" cy=\"74\" r=\"3\" fill=\"#1E1F24\"/><circle cx=\"72\" cy=\"74\" r=\"3\" fill=\"#1E1F24\"/><path d=\"M62 78 C64 81 66 81 68 78\" stroke=\"#1E1F24\" stroke-width=\"2\" stroke-linecap=\"round\"/><circle cx=\"52\" cy=\"98\" r=\"4.5\" fill=\"#1E1F24\"/><circle cx=\"64\" cy=\"100\" r=\"4.5\" fill=\"#1E1F24\"/><circle cx=\"76\" cy=\"98\" r=\"4.5\" fill=\"#1E1F24\"/><circle cx=\"58\" cy=\"92\" r=\"4.5\" fill=\"#1E1F24\"/><circle cx=\"70\" cy=\"92\" r=\"4.5\" fill=\"#1E1F24\"/></svg>",
  viewBox: '0 0 128 128',
};
