/**
 * Cute Bunny Emoji Data
 * Category: animals
 * Generated by scripts/generate.ts - DO NOT EDIT MANUALLY
 */
import { EmojiData, EmojiCategory } from '../types';

export const Bunny_DATA: EmojiData = {
  name: 'bunny' as EmojiData['name'],
  label: "Cute Bunny",
  category: 'animals' as EmojiCategory,
  keywords: ["bunny","rabbit","cute","ears","pet","hop","white"],
  unicode: "🐰",
  version: '1.1.0',
  svg: "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 128 128\" width=\"100%\" height=\"100%\" fill=\"none\"><path d=\"M42 56 C32 20 40 8 48 10 C56 12 56 34 50 56 Z\" fill=\"#FFFFFF\" stroke=\"#1E1F24\" stroke-width=\"4\" stroke-linejoin=\"round\"/><path d=\"M44 48 C38 24 42 16 46 16 C50 16 50 32 48 48 Z\" fill=\"#FFA3BA\"/><path d=\"M78 56 C72 34 72 12 80 10 C88 8 96 20 86 56 Z\" fill=\"#FFFFFF\" stroke=\"#1E1F24\" stroke-width=\"4\" stroke-linejoin=\"round\"/><path d=\"M80 48 C78 32 78 16 82 16 C86 16 90 24 84 48 Z\" fill=\"#FFA3BA\"/><ellipse cx=\"64\" cy=\"80\" rx=\"44\" ry=\"36\" fill=\"#FFFFFF\" stroke=\"#1E1F24\" stroke-width=\"4.5\"/><ellipse cx=\"32\" cy=\"86\" rx=\"10\" ry=\"6\" fill=\"#FFA3BA\" fill-opacity=\"0.8\"/><ellipse cx=\"96\" cy=\"86\" rx=\"10\" ry=\"6\" fill=\"#FFA3BA\" fill-opacity=\"0.8\"/><ellipse cx=\"46\" cy=\"72\" rx=\"7\" ry=\"9\" fill=\"#1E1F24\"/><circle cx=\"48\" cy=\"69\" r=\"2.8\" fill=\"#FFFFFF\"/><ellipse cx=\"82\" cy=\"72\" rx=\"7\" ry=\"9\" fill=\"#1E1F24\"/><circle cx=\"84\" cy=\"69\" r=\"2.8\" fill=\"#FFFFFF\"/><circle cx=\"64\" cy=\"78\" r=\"3.5\" fill=\"#FF8BA7\"/><path d=\"M56 84 C60 88 64 88 64 84 C64 88 68 88 72 84\" stroke=\"#1E1F24\" stroke-width=\"3\" stroke-linecap=\"round\"/></svg>",
  viewBox: '0 0 128 128',
};
