/**
 * Birthday Cake Emoji Data
 * Category: food
 * Generated by scripts/generate.ts - DO NOT EDIT MANUALLY
 */
import { EmojiData, EmojiCategory } from '../types';

export const Cake_DATA: EmojiData = {
  name: 'cake' as EmojiData['name'],
  label: "Birthday Cake",
  category: 'food' as EmojiCategory,
  keywords: ["cake","birthday","slice","strawberry","candle","sweet","party"],
  unicode: "🍰",
  version: '1.1.0',
  svg: "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 128 128\" width=\"100%\" height=\"100%\" fill=\"none\"><path d=\"M24 82 L96 46 L108 82 L36 112 Z\" fill=\"#FFE5D9\" stroke=\"#1E1F24\" stroke-width=\"4.5\" stroke-linejoin=\"round\"/><path d=\"M28 92 L98 58 L104 68 L32 100 Z\" fill=\"#FF4D6D\"/><path d=\"M22 82 L94 46 L106 46 L108 56 L34 92 Z\" fill=\"#FFFFFF\" stroke=\"#1E1F24\" stroke-width=\"3\"/><circle cx=\"54\" cy=\"62\" r=\"7\" fill=\"#E63946\" stroke=\"#1E1F24\" stroke-width=\"2.5\"/><circle cx=\"80\" cy=\"50\" r=\"7\" fill=\"#E63946\" stroke=\"#1E1F24\" stroke-width=\"2.5\"/><rect x=\"64\" y=\"28\" width=\"6\" height=\"24\" rx=\"2\" fill=\"#70D6FF\" stroke=\"#1E1F24\" stroke-width=\"2.5\"/><path d=\"M67 14 C61 20 63 26 67 28 C71 26 73 20 67 14 Z\" fill=\"#FFB703\" stroke=\"#1E1F24\" stroke-width=\"2\"/><circle cx=\"67\" cy=\"22\" r=\"2.5\" fill=\"#FF5E7E\"/></svg>",
  viewBox: '0 0 128 128',
};
