/**
 * Crying Cat Emoji Data
 * Category: animals
 * Generated by scripts/generate.ts - DO NOT EDIT MANUALLY
 */
import { EmojiData, EmojiCategory } from '../types';

export const CatCry_DATA: EmojiData = {
  name: 'cat-cry' as EmojiData['name'],
  label: "Crying Cat",
  category: 'animals' as EmojiCategory,
  keywords: ["cat","kitty","cry","tears","sad","weep","whimper"],
  unicode: "😿",
  version: '1.1.0',
  svg: "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 128 128\" width=\"100%\" height=\"100%\" fill=\"none\"><path d=\"M24 48 L36 26 L52 44 Z\" fill=\"#FFE5D9\" stroke=\"#1E1F24\" stroke-width=\"4\" stroke-linejoin=\"round\"/><path d=\"M104 48 L92 26 L76 44 Z\" fill=\"#FFE5D9\" stroke=\"#1E1F24\" stroke-width=\"4\" stroke-linejoin=\"round\"/><ellipse cx=\"64\" cy=\"72\" rx=\"46\" ry=\"38\" fill=\"#FFF0F5\" stroke=\"#1E1F24\" stroke-width=\"4.5\"/><path d=\"M42 62 C40 82 36 94 36 104 C44 104 46 84 46 62 Z\" fill=\"#70D6FF\" stroke=\"#1E1F24\" stroke-width=\"2.5\"/><path d=\"M86 62 C88 82 92 94 92 104 C84 104 82 84 82 62 Z\" fill=\"#70D6FF\" stroke=\"#1E1F24\" stroke-width=\"2.5\"/><ellipse cx=\"44\" cy=\"58\" rx=\"7\" ry=\"8\" fill=\"#1E1F24\"/><ellipse cx=\"84\" cy=\"58\" rx=\"7\" ry=\"8\" fill=\"#1E1F24\"/><path d=\"M56 82 C60 76 68 76 72 82\" stroke=\"#1E1F24\" stroke-width=\"3.5\" stroke-linecap=\"round\"/><line x1=\"20\" y1=\"74\" x2=\"32\" y2=\"76\" stroke=\"#1E1F24\" stroke-width=\"2.5\" stroke-linecap=\"round\"/><line x1=\"108\" y1=\"74\" x2=\"96\" y2=\"76\" stroke=\"#1E1F24\" stroke-width=\"2.5\" stroke-linecap=\"round\"/></svg>",
  viewBox: '0 0 128 128',
};
