/**
 * Cherry Blossom Sakura Emoji Data
 * Category: symbols
 * Generated by scripts/generate.ts - DO NOT EDIT MANUALLY
 */
import { EmojiData, EmojiCategory } from '../types';

export const CherryBlossom_DATA: EmojiData = {
  name: 'cherry-blossom' as EmojiData['name'],
  label: "Cherry Blossom Sakura",
  category: 'symbols' as EmojiCategory,
  keywords: ["flower","cherry","blossom","sakura","pink","spring","nature","bloom"],
  unicode: "🌸",
  version: '1.1.0',
  svg: "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 128 128\" width=\"100%\" height=\"100%\" fill=\"none\"><g transform=\"translate(64 64)\"><path d=\"M0 -10 C-14 -20 -12 -48 0 -54 C12 -48 14 -20 0 -10 Z\" fill=\"#FFA3BA\" stroke=\"#1E1F24\" stroke-width=\"3.5\" stroke-linejoin=\"round\"/><path d=\"M0 -10 C-14 -20 -12 -48 0 -54 C12 -48 14 -20 0 -10 Z\" fill=\"#FFA3BA\" stroke=\"#1E1F24\" stroke-width=\"3.5\" stroke-linejoin=\"round\" transform=\"rotate(72)\"/><path d=\"M0 -10 C-14 -20 -12 -48 0 -54 C12 -48 14 -20 0 -10 Z\" fill=\"#FFA3BA\" stroke=\"#1E1F24\" stroke-width=\"3.5\" stroke-linejoin=\"round\" transform=\"rotate(144)\"/><path d=\"M0 -10 C-14 -20 -12 -48 0 -54 C12 -48 14 -20 0 -10 Z\" fill=\"#FFA3BA\" stroke=\"#1E1F24\" stroke-width=\"3.5\" stroke-linejoin=\"round\" transform=\"rotate(216)\"/><path d=\"M0 -10 C-14 -20 -12 -48 0 -54 C12 -48 14 -20 0 -10 Z\" fill=\"#FFA3BA\" stroke=\"#1E1F24\" stroke-width=\"3.5\" stroke-linejoin=\"round\" transform=\"rotate(288)\"/><circle cx=\"0\" cy=\"0\" r=\"14\" fill=\"#FFCCD5\"/><circle cx=\"0\" cy=\"0\" r=\"8\" fill=\"#FF758F\"/><circle cx=\"0\" cy=\"-6\" r=\"2\" fill=\"#FFD166\"/><circle cx=\"6\" cy=\"-2\" r=\"2\" fill=\"#FFD166\"/><circle cx=\"4\" cy=\"5\" r=\"2\" fill=\"#FFD166\"/><circle cx=\"-4\" cy=\"5\" r=\"2\" fill=\"#FFD166\"/><circle cx=\"-6\" cy=\"-2\" r=\"2\" fill=\"#FFD166\"/></g></svg>",
  viewBox: '0 0 128 128',
};
