/**
 * Hot Coffee Emoji Data
 * Category: food
 * Generated by scripts/generate.ts - DO NOT EDIT MANUALLY
 */
import { EmojiData, EmojiCategory } from '../types';

export const Coffee_DATA: EmojiData = {
  name: 'coffee' as EmojiData['name'],
  label: "Hot Coffee",
  category: 'food' as EmojiCategory,
  keywords: ["coffee","tea","mug","latte","espresso","morning","caffeine"],
  unicode: "☕",
  version: '1.1.0',
  svg: "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 128 128\" width=\"100%\" height=\"100%\" fill=\"none\"><ellipse cx=\"64\" cy=\"106\" rx=\"44\" ry=\"10\" fill=\"#E8E2D7\" stroke=\"#1E1F24\" stroke-width=\"4\"/><path d=\"M84 60 C98 60 98 84 84 84\" stroke=\"#1E1F24\" stroke-width=\"5\" fill=\"none\"/><path d=\"M36 50 L40 98 C40 104 88 104 88 98 L92 50 Z\" fill=\"#FFFFFF\" stroke=\"#1E1F24\" stroke-width=\"4.5\" stroke-linejoin=\"round\"/><ellipse cx=\"64\" cy=\"52\" rx=\"26\" ry=\"7\" fill=\"#6F4E37\"/><path d=\"M64 54 C61 50 56 50 54 53 C52 56 57 60 64 63 C71 60 76 56 74 53 C72 50 67 50 64 54 Z\" fill=\"#FFF3B0\"/><path d=\"M54 36 C50 28 58 24 64 28 C70 24 78 28 74 36 L64 44 Z\" fill=\"#FFA3BA\" stroke=\"#1E1F24\" stroke-width=\"2\"/></svg>",
  viewBox: '0 0 128 128',
};
