/**
 * Confused Emoji Data
 * Category: emotions
 * Generated by scripts/generate.ts - DO NOT EDIT MANUALLY
 */
import { EmojiData, EmojiCategory } from '../types';

export const Confused_DATA: EmojiData = {
  name: 'confused' as EmojiData['name'],
  label: "Confused",
  category: 'emotions' as EmojiCategory,
  keywords: ["confused","puzzled","huh","unsure","derp","sweat"],
  unicode: "😕",
  version: '1.0.0',
  svg: "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 128 128\" width=\"100%\" height=\"100%\" fill=\"none\"><ellipse cx=\"26\" cy=\"74\" rx=\"14\" ry=\"8\" fill=\"#FFA3BA\" fill-opacity=\"0.6\"/><ellipse cx=\"102\" cy=\"74\" rx=\"14\" ry=\"8\" fill=\"#FFA3BA\" fill-opacity=\"0.6\"/><path d=\"M26 34 C32 26 44 26 52 32\" stroke=\"#1E1F24\" stroke-width=\"4.5\" stroke-linecap=\"round\"/><path d=\"M76 40 C84 42 96 38 102 34\" stroke=\"#1E1F24\" stroke-width=\"4.5\" stroke-linecap=\"round\"/><circle cx=\"40\" cy=\"52\" r=\"10\" fill=\"#FFFFFF\" stroke=\"#1E1F24\" stroke-width=\"3.5\"/><circle cx=\"40\" cy=\"52\" r=\"5\" fill=\"#1E1F24\"/><circle cx=\"42\" cy=\"50\" r=\"1.8\" fill=\"#FFFFFF\"/><ellipse cx=\"88\" cy=\"54\" rx=\"7\" ry=\"9\" fill=\"#1E1F24\"/><circle cx=\"89\" cy=\"51\" r=\"2.5\" fill=\"#FFFFFF\"/><path d=\"M102 24 C100 28 96 34 96 38 C96 42 99 45 103 45 C107 45 110 42 110 38 C110 34 106 28 102 24 Z\" fill=\"#70D6FF\" stroke=\"#1E1F24\" stroke-width=\"2.5\" stroke-linejoin=\"round\"/><path d=\"M44 80 C50 86 58 76 66 84 C74 90 82 78 86 82\" stroke=\"#1E1F24\" stroke-width=\"4.5\" stroke-linecap=\"round\"/></svg>",
  viewBox: '0 0 128 128',
};
