/**
 * Crying Waterfall Emoji Data
 * Category: emotions
 * Generated by scripts/generate.ts - DO NOT EDIT MANUALLY
 */
import { EmojiData, EmojiCategory } from '../types';

export const Cry_DATA: EmojiData = {
  name: 'cry' as EmojiData['name'],
  label: "Crying Waterfall",
  category: 'emotions' as EmojiCategory,
  keywords: ["cry","tears","sad","weep","waterfall","sobbing"],
  unicode: "😭",
  version: '1.0.0',
  svg: "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 128 128\" width=\"100%\" height=\"100%\" fill=\"none\"><ellipse cx=\"22\" cy=\"80\" rx=\"14\" ry=\"8\" fill=\"#FFA3BA\" fill-opacity=\"0.6\"/><ellipse cx=\"106\" cy=\"80\" rx=\"14\" ry=\"8\" fill=\"#FFA3BA\" fill-opacity=\"0.6\"/><path d=\"M26 36 C34 26 44 26 52 34\" stroke=\"#1E1F24\" stroke-width=\"4.5\" stroke-linecap=\"round\"/><path d=\"M76 34 C84 26 94 26 102 36\" stroke=\"#1E1F24\" stroke-width=\"4.5\" stroke-linecap=\"round\"/><path d=\"M28 50 C36 42 46 42 54 50\" stroke=\"#1E1F24\" stroke-width=\"5\" stroke-linecap=\"round\"/><path d=\"M74 50 C82 42 92 42 100 50\" stroke=\"#1E1F24\" stroke-width=\"5\" stroke-linecap=\"round\"/><path d=\"M36 54 C34 70 30 90 32 116 C38 116 46 116 48 116 C46 90 44 70 44 54 Z\" fill=\"#4CC9F0\" fill-opacity=\"0.8\" stroke=\"#1E1F24\" stroke-width=\"3\" stroke-linejoin=\"round\"/><path d=\"M20 102 Q16 98 12 100\" stroke=\"#4CC9F0\" stroke-width=\"3\" stroke-linecap=\"round\"/><path d=\"M22 112 Q16 114 14 118\" stroke=\"#4CC9F0\" stroke-width=\"3\" stroke-linecap=\"round\"/><path d=\"M84 54 C84 70 82 90 80 116 C82 116 90 116 96 116 C98 90 94 70 92 54 Z\" fill=\"#4CC9F0\" fill-opacity=\"0.8\" stroke=\"#1E1F24\" stroke-width=\"3\" stroke-linejoin=\"round\"/><path d=\"M108 102 Q112 98 116 100\" stroke=\"#4CC9F0\" stroke-width=\"3\" stroke-linecap=\"round\"/><path d=\"M106 112 Q112 114 114 118\" stroke=\"#4CC9F0\" stroke-width=\"3\" stroke-linecap=\"round\"/><path d=\"M46 76 C46 76 50 102 64 102 C78 102 82 76 82 76 Z\" fill=\"#E63946\" stroke=\"#1E1F24\" stroke-width=\"4.5\" stroke-linejoin=\"round\"/><path d=\"M52 94 C56 88 72 88 76 94 Z\" fill=\"#FF85A1\"/></svg>",
  viewBox: '0 0 128 128',
};
