/**
 * Cute Poop Emoji Data
 * Category: fun
 * Generated by scripts/generate.ts - DO NOT EDIT MANUALLY
 */
import { EmojiData, EmojiCategory } from '../types';

export const CutePoop_DATA: EmojiData = {
  name: 'cute-poop' as EmojiData['name'],
  label: "Cute Poop",
  category: 'fun' as EmojiCategory,
  keywords: ["poop","cute","swirl","funny","kawaii","brown"],
  unicode: "💩",
  version: '1.1.0',
  svg: "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 128 128\" width=\"100%\" height=\"100%\" fill=\"none\"><path d=\"M64 22 C64 22 72 24 74 30 C76 36 68 40 68 40 C78 40 88 44 88 52 C88 58 82 62 78 64 C90 64 102 70 102 82 C102 96 90 106 64 106 C38 106 26 96 26 82 C26 70 38 64 50 64 C46 62 40 58 40 52 C40 44 50 40 60 40 C60 40 52 36 54 30 C56 24 64 22 64 22 Z\" fill=\"#9C6644\" stroke=\"#1E1F24\" stroke-width=\"4.5\" stroke-linejoin=\"round\"/><ellipse cx=\"40\" cy=\"86\" rx=\"8\" ry=\"5\" fill=\"#FFA3BA\" fill-opacity=\"0.8\"/><ellipse cx=\"88\" cy=\"86\" rx=\"8\" ry=\"5\" fill=\"#FFA3BA\" fill-opacity=\"0.8\"/><circle cx=\"50\" cy=\"74\" r=\"8\" fill=\"#1E1F24\"/><circle cx=\"53\" cy=\"71\" r=\"3\" fill=\"#FFFFFF\"/><circle cx=\"78\" cy=\"74\" r=\"8\" fill=\"#1E1F24\"/><circle cx=\"81\" cy=\"71\" r=\"3\" fill=\"#FFFFFF\"/><path d=\"M56 86 C60 92 68 92 72 86\" stroke=\"#1E1F24\" stroke-width=\"3.5\" stroke-linecap=\"round\"/></svg>",
  viewBox: '0 0 128 128',
};
