/**
 * Sparkling Diamond Emoji Data
 * Category: objects
 * Generated by scripts/generate.ts - DO NOT EDIT MANUALLY
 */
import { EmojiData, EmojiCategory } from '../types';

export const Diamond_DATA: EmojiData = {
  name: 'diamond' as EmojiData['name'],
  label: "Sparkling Diamond",
  category: 'objects' as EmojiCategory,
  keywords: ["diamond","gem","jewel","crystal","sparkle","precious","luxury"],
  unicode: "💎",
  version: '1.1.0',
  svg: "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 128 128\" width=\"100%\" height=\"100%\" fill=\"none\"><path d=\"M38 42 L90 42 L112 62 L16 62 Z\" fill=\"#70D6FF\" stroke=\"#1E1F24\" stroke-width=\"4.5\" stroke-linejoin=\"round\"/><path d=\"M16 62 L64 112 L112 62 Z\" fill=\"#00B4D8\" stroke=\"#1E1F24\" stroke-width=\"4.5\" stroke-linejoin=\"round\"/><path d=\"M38 42 L52 62 L64 112 L76 62 L90 42\" stroke=\"#1E1F24\" stroke-width=\"3.5\" stroke-linejoin=\"round\" fill=\"none\"/><path d=\"M52 62 L76 62\" stroke=\"#1E1F24\" stroke-width=\"3\"/><polygon points=\"52,46 64,46 58,58\" fill=\"#E8F8FF\"/><path d=\"M22 28 L24 34 L30 36 L24 38 L22 44 L20 38 L14 36 L20 34 Z\" fill=\"#FFFFFF\"/></svg>",
  viewBox: '0 0 128 128',
};
