/**
 * Happy Puppy Emoji Data
 * Category: animals
 * Generated by scripts/generate.ts - DO NOT EDIT MANUALLY
 */
import { EmojiData, EmojiCategory } from '../types';

export const DogPuppy_DATA: EmojiData = {
  name: 'dog-puppy' as EmojiData['name'],
  label: "Happy Puppy",
  category: 'animals' as EmojiCategory,
  keywords: ["dog","puppy","pup","bark","woof","pet","cute","ears"],
  unicode: "🐶",
  version: '1.1.0',
  svg: "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 128 128\" width=\"100%\" height=\"100%\" fill=\"none\"><path d=\"M34 40 C14 42 12 76 26 84 C34 88 40 76 38 52 Z\" fill=\"#8D6E63\" stroke=\"#1E1F24\" stroke-width=\"4\" stroke-linejoin=\"round\"/><path d=\"M94 40 C114 42 116 76 102 84 C94 88 88 76 90 52 Z\" fill=\"#8D6E63\" stroke=\"#1E1F24\" stroke-width=\"4\" stroke-linejoin=\"round\"/><circle cx=\"64\" cy=\"72\" r=\"42\" fill=\"#D7CCC8\" stroke=\"#1E1F24\" stroke-width=\"4.5\"/><ellipse cx=\"36\" cy=\"78\" rx=\"8\" ry=\"5\" fill=\"#FFA3BA\" fill-opacity=\"0.8\"/><ellipse cx=\"92\" cy=\"78\" rx=\"8\" ry=\"5\" fill=\"#FFA3BA\" fill-opacity=\"0.8\"/><ellipse cx=\"46\" cy=\"62\" rx=\"7\" ry=\"8\" fill=\"#1E1F24\"/><circle cx=\"48\" cy=\"59\" r=\"2.8\" fill=\"#FFFFFF\"/><ellipse cx=\"82\" cy=\"62\" rx=\"7\" ry=\"8\" fill=\"#1E1F24\"/><circle cx=\"84\" cy=\"59\" r=\"2.8\" fill=\"#FFFFFF\"/><ellipse cx=\"64\" cy=\"74\" rx=\"8\" ry=\"6\" fill=\"#1E1F24\"/><path d=\"M54 84 C58 98 70 98 74 84\" stroke=\"#1E1F24\" stroke-width=\"3\" fill=\"#FF5E7E\"/></svg>",
  viewBox: '0 0 128 128',
};
