/**
 * Drooling / Yummy Emoji Data
 * Category: faces
 * Generated by scripts/generate.ts - DO NOT EDIT MANUALLY
 */
import { EmojiData, EmojiCategory } from '../types';

export const Drool_DATA: EmojiData = {
  name: 'drool' as EmojiData['name'],
  label: "Drooling / Yummy",
  category: 'faces' as EmojiCategory,
  keywords: ["drool","yummy","delicious","hungry","craving","tasty"],
  unicode: "🤤",
  version: '1.1.0',
  svg: "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 128 128\" width=\"100%\" height=\"100%\" fill=\"none\"><ellipse cx=\"28\" cy=\"74\" rx=\"14\" ry=\"9\" fill=\"#FFA3BA\" fill-opacity=\"0.65\"/><ellipse cx=\"100\" cy=\"74\" rx=\"14\" ry=\"9\" fill=\"#FFA3BA\" fill-opacity=\"0.65\"/><path d=\"M34 54 C40 46 48 46 54 54\" stroke=\"#1E1F24\" stroke-width=\"5\" stroke-linecap=\"round\"/><path d=\"M74 54 C80 46 88 46 94 54\" stroke=\"#1E1F24\" stroke-width=\"5\" stroke-linecap=\"round\"/><path d=\"M44 72 C44 72 52 90 70 90 C78 90 84 82 84 72 Z\" fill=\"#FF5E7E\" stroke=\"#1E1F24\" stroke-width=\"4.5\" stroke-linejoin=\"round\"/><path d=\"M76 86 C82 90 84 102 78 106 C72 106 72 96 76 86 Z\" fill=\"#70D6FF\" stroke=\"#1E1F24\" stroke-width=\"3\" stroke-linejoin=\"round\"/></svg>",
  viewBox: '0 0 128 128',
};
