/**
 * Frog in Love Emoji Data
 * Category: animals
 * Generated by scripts/generate.ts - DO NOT EDIT MANUALLY
 */
import { EmojiData, EmojiCategory } from '../types';

export const FrogLove_DATA: EmojiData = {
  name: 'frog-love' as EmojiData['name'],
  label: "Frog in Love",
  category: 'animals' as EmojiCategory,
  keywords: ["frog","love","heart","crush","cute","ribbit","holding"],
  unicode: "🐸",
  version: '1.1.0',
  svg: "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 128 128\" width=\"100%\" height=\"100%\" fill=\"none\"><path d=\"M24 64 C24 44 32 38 42 38 C48 38 52 42 56 46 C60 46 68 46 72 46 C76 42 80 38 86 38 C96 38 104 44 104 64 C104 90 92 108 64 108 C36 108 24 90 24 64 Z\" fill=\"#AACC00\" stroke=\"#1E1F24\" stroke-width=\"4.5\" stroke-linejoin=\"round\"/><path d=\"M40 82 C40 70 50 64 64 64 C78 64 88 70 88 82 C88 98 78 104 64 104 C50 104 40 98 40 82 Z\" fill=\"#E9F5DB\"/><circle cx=\"44\" cy=\"38\" r=\"14\" fill=\"#AACC00\" stroke=\"#1E1F24\" stroke-width=\"4\"/><circle cx=\"84\" cy=\"38\" r=\"14\" fill=\"#AACC00\" stroke=\"#1E1F24\" stroke-width=\"4\"/><path d=\"M44 34 C40 28 48 24 50 30 C52 24 60 28 56 34 L50 42 Z\" fill=\"#FF3366\" stroke=\"#1E1F24\" stroke-width=\"1.8\" transform=\"translate(-6 -2) scale(1.1)\"/><path d=\"M84 34 C80 28 88 24 90 30 C92 24 100 28 96 34 L90 42 Z\" fill=\"#FF3366\" stroke=\"#1E1F24\" stroke-width=\"1.8\" transform=\"translate(-6 -2) scale(1.1)\"/><ellipse cx=\"34\" cy=\"68\" rx=\"8\" ry=\"5\" fill=\"#FF8BA7\" fill-opacity=\"0.85\"/><ellipse cx=\"94\" cy=\"68\" rx=\"8\" ry=\"5\" fill=\"#FF8BA7\" fill-opacity=\"0.85\"/><path d=\"M64 72 C56 58 72 50 78 58 C84 50 100 58 92 72 L78 88 Z\" fill=\"#FF4D6D\" stroke=\"#1E1F24\" stroke-width=\"3.5\" stroke-linejoin=\"round\" transform=\"translate(-14 10) scale(0.9)\"/></svg>",
  viewBox: '0 0 128 128',
};
