/**
 * Natural Frog Emoji Data
 * Category: animals
 * Generated by scripts/generate.ts - DO NOT EDIT MANUALLY
 */
import { EmojiData, EmojiCategory } from '../types';

export const FrogNatural_DATA: EmojiData = {
  name: 'frog-natural' as EmojiData['name'],
  label: "Natural Frog",
  category: 'animals' as EmojiCategory,
  keywords: ["frog","natural","calm","neutral","zen","peaceful","chill"],
  unicode: "🐸",
  version: '1.1.0',
  svg: "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 128 128\" width=\"100%\" height=\"100%\" fill=\"none\"><path d=\"M24 64 C24 44 32 38 42 38 C48 38 52 42 56 46 C60 46 68 46 72 46 C76 42 80 38 86 38 C96 38 104 44 104 64 C104 90 92 108 64 108 C36 108 24 90 24 64 Z\" fill=\"#AACC00\" stroke=\"#1E1F24\" stroke-width=\"4.5\" stroke-linejoin=\"round\"/><path d=\"M40 82 C40 70 50 64 64 64 C78 64 88 70 88 82 C88 98 78 104 64 104 C50 104 40 98 40 82 Z\" fill=\"#E9F5DB\"/><circle cx=\"44\" cy=\"38\" r=\"14\" fill=\"#AACC00\" stroke=\"#1E1F24\" stroke-width=\"4\"/><circle cx=\"44\" cy=\"38\" r=\"6.5\" fill=\"#1E1F24\"/><circle cx=\"46\" cy=\"36\" r=\"2.2\" fill=\"#FFFFFF\"/><circle cx=\"84\" cy=\"38\" r=\"14\" fill=\"#AACC00\" stroke=\"#1E1F24\" stroke-width=\"4\"/><circle cx=\"84\" cy=\"38\" r=\"6.5\" fill=\"#1E1F24\"/><circle cx=\"86\" cy=\"36\" r=\"2.2\" fill=\"#FFFFFF\"/><ellipse cx=\"34\" cy=\"68\" rx=\"8\" ry=\"5\" fill=\"#FF8BA7\" fill-opacity=\"0.5\"/><ellipse cx=\"94\" cy=\"68\" rx=\"8\" ry=\"5\" fill=\"#FF8BA7\" fill-opacity=\"0.5\"/><path d=\"M48 76 C54 78 74 78 80 76\" stroke=\"#1E1F24\" stroke-width=\"3.5\" stroke-linecap=\"round\" fill=\"none\"/><path d=\"M24 72 C18 70 14 64 16 58 C18 54 22 58 24 64\" stroke=\"#1E1F24\" stroke-width=\"3.5\" stroke-linecap=\"round\" fill=\"#AACC00\"/><path d=\"M104 72 C110 70 114 64 112 58 C110 54 106 58 104 64\" stroke=\"#1E1F24\" stroke-width=\"3.5\" stroke-linecap=\"round\" fill=\"#AACC00\"/></svg>",
  viewBox: '0 0 128 128',
};
