/**
 * Friendly Ghost Emoji Data
 * Category: fun
 * Generated by scripts/generate.ts - DO NOT EDIT MANUALLY
 */
import { EmojiData, EmojiCategory } from '../types';

export const Ghost_DATA: EmojiData = {
  name: 'ghost' as EmojiData['name'],
  label: "Friendly Ghost",
  category: 'fun' as EmojiCategory,
  keywords: ["ghost","boo","cute","spooky","halloween","spirit","floating"],
  unicode: "👻",
  version: '1.1.0',
  svg: "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 128 128\" width=\"100%\" height=\"100%\" fill=\"none\"><path d=\"M64 24 C40 24 30 42 30 68 C30 92 32 104 40 100 C48 96 52 104 60 100 C68 96 72 104 80 100 C88 96 92 104 98 100 C100 88 98 68 98 68 C98 42 88 24 64 24 Z\" fill=\"#F8F9FA\" stroke=\"#1E1F24\" stroke-width=\"4.5\" stroke-linejoin=\"round\"/><ellipse cx=\"42\" cy=\"66\" rx=\"8\" ry=\"5\" fill=\"#FFA3BA\" fill-opacity=\"0.8\"/><ellipse cx=\"86\" cy=\"66\" rx=\"8\" ry=\"5\" fill=\"#FFA3BA\" fill-opacity=\"0.8\"/><path d=\"M30 64 C20 60 18 72 28 74\" stroke=\"#1E1F24\" stroke-width=\"4\" stroke-linecap=\"round\" fill=\"#F8F9FA\"/><path d=\"M98 64 C108 60 110 72 100 74\" stroke=\"#1E1F24\" stroke-width=\"4\" stroke-linecap=\"round\" fill=\"#F8F9FA\"/><circle cx=\"50\" cy=\"52\" r=\"6\" fill=\"#1E1F24\"/><circle cx=\"52\" cy=\"50\" r=\"2.2\" fill=\"#FFFFFF\"/><circle cx=\"78\" cy=\"52\" r=\"6\" fill=\"#1E1F24\"/><circle cx=\"80\" cy=\"50\" r=\"2.2\" fill=\"#FFFFFF\"/><ellipse cx=\"64\" cy=\"68\" rx=\"6\" ry=\"8\" fill=\"#FF5E7E\" stroke=\"#1E1F24\" stroke-width=\"3.5\"/></svg>",
  viewBox: '0 0 128 128',
};
