/**
 * Happy Emoji Data
 * Category: faces
 * Generated by scripts/generate.ts - DO NOT EDIT MANUALLY
 */
import { EmojiData, EmojiCategory } from '../types';

export const Happy_DATA: EmojiData = {
  name: 'happy' as EmojiData['name'],
  label: "Happy",
  category: 'faces' as EmojiCategory,
  keywords: ["happy","smile","joy","cheerful","positive","smiling","blush"],
  unicode: "😊",
  version: '1.0.0',
  svg: "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 128 128\" width=\"100%\" height=\"100%\" fill=\"none\"><ellipse cx=\"28\" cy=\"74\" rx=\"14\" ry=\"9\" fill=\"#FFA3BA\" fill-opacity=\"0.65\"/><ellipse cx=\"100\" cy=\"74\" rx=\"14\" ry=\"9\" fill=\"#FFA3BA\" fill-opacity=\"0.65\"/><path d=\"M30 36 C36 30 48 30 54 35\" stroke=\"#1E1F24\" stroke-width=\"4.5\" stroke-linecap=\"round\"/><path d=\"M74 35 C80 30 92 30 98 36\" stroke=\"#1E1F24\" stroke-width=\"4.5\" stroke-linecap=\"round\"/><ellipse cx=\"42\" cy=\"54\" rx=\"9\" ry=\"11\" fill=\"#1E1F24\"/><circle cx=\"45\" cy=\"51\" r=\"3.5\" fill=\"#FFFFFF\"/><circle cx=\"39\" cy=\"57\" r=\"1.8\" fill=\"#FFFFFF\"/><ellipse cx=\"86\" cy=\"54\" rx=\"9\" ry=\"11\" fill=\"#1E1F24\"/><circle cx=\"89\" cy=\"51\" r=\"3.5\" fill=\"#FFFFFF\"/><circle cx=\"83\" cy=\"57\" r=\"1.8\" fill=\"#FFFFFF\"/><circle cx=\"64\" cy=\"67\" r=\"2.2\" fill=\"#1E1F24\"/><path d=\"M46 76 C52 92 76 92 82 76\" stroke=\"#1E1F24\" stroke-width=\"4.5\" stroke-linecap=\"round\" fill=\"#FF5E7E\"/><path d=\"M52 82 C58 80 70 80 76 82\" stroke=\"#FFFFFF\" stroke-width=\"2.5\" stroke-linecap=\"round\"/></svg>",
  viewBox: '0 0 128 128',
};
