/**
 * Heart Hands Emoji Data
 * Category: gestures
 * Generated by scripts/generate.ts - DO NOT EDIT MANUALLY
 */
import { EmojiData, EmojiCategory } from '../types';

export const HeartHands_DATA: EmojiData = {
  name: 'heart-hands' as EmojiData['name'],
  label: "Heart Hands",
  category: 'gestures' as EmojiCategory,
  keywords: ["heart","hands","love","gesture","cute","kpop","adore"],
  unicode: "🫶",
  version: '1.1.0',
  svg: "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 128 128\" width=\"100%\" height=\"100%\" fill=\"none\"><path d=\"M24 78 C20 64 26 48 38 42 C48 38 56 46 64 56 C72 46 80 38 90 42 C102 48 108 64 104 78 C98 94 76 104 64 108 C52 104 30 94 24 78 Z\" fill=\"#FFE5D9\" stroke=\"#1E1F24\" stroke-width=\"4.5\" stroke-linejoin=\"round\"/><path d=\"M64 62 C58 54 48 54 44 62 C40 70 52 82 64 90 C76 82 88 70 84 62 C80 54 70 54 64 62 Z\" fill=\"#FF4D6D\" stroke=\"#1E1F24\" stroke-width=\"3\" stroke-linejoin=\"round\"/><path d=\"M38 42 C42 50 44 62 44 70\" stroke=\"#1E1F24\" stroke-width=\"3.5\" stroke-linecap=\"round\"/><path d=\"M90 42 C86 50 84 62 84 70\" stroke=\"#1E1F24\" stroke-width=\"3.5\" stroke-linecap=\"round\"/><ellipse cx=\"64\" cy=\"74\" rx=\"6\" ry=\"6\" fill=\"#FF85A1\"/></svg>",
  viewBox: '0 0 128 128',
};
