/**
 * Sparkling Heart Emoji Data
 * Category: love
 * Generated by scripts/generate.ts - DO NOT EDIT MANUALLY
 */
import { EmojiData, EmojiCategory } from '../types';

export const Heart_DATA: EmojiData = {
  name: 'heart' as EmojiData['name'],
  label: "Sparkling Heart",
  category: 'love' as EmojiCategory,
  keywords: ["heart","love","like","sparkle","favorite","red"],
  unicode: "💖",
  version: '1.0.0',
  svg: "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 128 128\" width=\"100%\" height=\"100%\" fill=\"none\"><g transform=\"translate(64, 62) scale(1.15)\"><path d=\"M0,18 A16,16 0 0,0 -30,-12 A16,16 0 0,0 -48,18 Q-48,44 0,72 Q48,44 48,18 A16,16 0 0,0 30,-12 A16,16 0 0,0 0,18 Z\" transform=\"translate(0, -26)\" fill=\"#FF2A6D\" stroke=\"#1E1F24\" stroke-width=\"4.5\" stroke-linejoin=\"round\"/><path d=\"M-34 -14 C-42 -4 -42 12 -38 24\" stroke=\"#FFFFFF\" stroke-width=\"4.5\" stroke-linecap=\"round\"/><circle cx=\"-24\" cy=\"-18\" r=\"3\" fill=\"#FFFFFF\"/></g><polygon points=\"106,18 109,24 116,24 111,28 113,34 106,30 99,34 101,28 96,24 103,24\" fill=\"#FFD166\"/><polygon points=\"20,84 22,88 28,88 24,91 25,96 20,93 15,96 16,91 12,88 18,88\" fill=\"#FFD166\"/></svg>",
  viewBox: '0 0 128 128',
};
