/**
 * 100 Points Emoji Data
 * Category: symbols
 * Generated by scripts/generate.ts - DO NOT EDIT MANUALLY
 */
import { EmojiData, EmojiCategory } from '../types';

export const Hundred_DATA: EmojiData = {
  name: 'hundred' as EmojiData['name'],
  label: "100 Points",
  category: 'symbols' as EmojiCategory,
  keywords: ["100","hundred","score","perfect","points","grade","fire"],
  unicode: "💯",
  version: '1.1.0',
  svg: "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 128 128\" width=\"100%\" height=\"100%\" fill=\"none\"><g transform=\"rotate(-12 64 64)\"><path d=\"M26 44 L38 34 L38 88 L26 88\" stroke=\"#E63946\" stroke-width=\"8\" stroke-linecap=\"round\" stroke-linejoin=\"round\" fill=\"none\"/><ellipse cx=\"62\" cy=\"62\" rx=\"14\" ry=\"24\" stroke=\"#E63946\" stroke-width=\"8\" fill=\"none\"/><ellipse cx=\"98\" cy=\"62\" rx=\"14\" ry=\"24\" stroke=\"#E63946\" stroke-width=\"8\" fill=\"none\"/><line x1=\"20\" y1=\"98\" x2=\"114\" y2=\"98\" stroke=\"#E63946\" stroke-width=\"6\" stroke-linecap=\"round\"/><line x1=\"24\" y1=\"108\" x2=\"110\" y2=\"108\" stroke=\"#E63946\" stroke-width=\"6\" stroke-linecap=\"round\"/></g></svg>",
  viewBox: '0 0 128 128',
};
