/**
 * Soft Serve Ice Cream Emoji Data
 * Category: food
 * Generated by scripts/generate.ts - DO NOT EDIT MANUALLY
 */
import { EmojiData, EmojiCategory } from '../types';

export const IceCream_DATA: EmojiData = {
  name: 'ice-cream' as EmojiData['name'],
  label: "Soft Serve Ice Cream",
  category: 'food' as EmojiCategory,
  keywords: ["icecream","cone","softserve","sweet","dessert","summer","treat"],
  unicode: "🍦",
  version: '1.1.0',
  svg: "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 128 128\" width=\"100%\" height=\"100%\" fill=\"none\"><path d=\"M42 66 L64 116 L86 66 Z\" fill=\"#DDB892\" stroke=\"#1E1F24\" stroke-width=\"4.5\" stroke-linejoin=\"round\"/><line x1=\"48\" y1=\"76\" x2=\"78\" y2=\"88\" stroke=\"#B08968\" stroke-width=\"2.5\"/><line x1=\"56\" y1=\"92\" x2=\"72\" y2=\"98\" stroke=\"#B08968\" stroke-width=\"2.5\"/><path d=\"M34 66 C34 56 46 54 64 54 C82 54 94 56 94 66 C94 72 34 72 34 66 Z\" fill=\"#FFA3BA\" stroke=\"#1E1F24\" stroke-width=\"4\" stroke-linejoin=\"round\"/><path d=\"M40 54 C40 44 50 42 64 42 C78 42 88 44 88 54 Z\" fill=\"#FFF3B0\" stroke=\"#1E1F24\" stroke-width=\"4\" stroke-linejoin=\"round\"/><path d=\"M48 42 C48 26 64 16 68 22 C68 28 68 34 80 42 Z\" fill=\"#B7E4C7\" stroke=\"#1E1F24\" stroke-width=\"4\" stroke-linejoin=\"round\"/><line x1=\"52\" y1=\"48\" x2=\"58\" y2=\"48\" stroke=\"#FF5E7E\" stroke-width=\"3\" stroke-linecap=\"round\"/><line x1=\"72\" y1=\"50\" x2=\"78\" y2=\"48\" stroke=\"#70D6FF\" stroke-width=\"3\" stroke-linecap=\"round\"/><line x1=\"62\" y1=\"36\" x2=\"68\" y2=\"34\" stroke=\"#FFD166\" stroke-width=\"3\" stroke-linecap=\"round\"/><circle cx=\"64\" cy=\"14\" r=\"3\" fill=\"#FF5E7E\"/></svg>",
  viewBox: '0 0 128 128',
};
