/**
 * Laughing Emoji Data
 * Category: faces
 * Generated by scripts/generate.ts - DO NOT EDIT MANUALLY
 */
import { EmojiData, EmojiCategory } from '../types';

export const Laugh_DATA: EmojiData = {
  name: 'laugh' as EmojiData['name'],
  label: "Laughing",
  category: 'faces' as EmojiCategory,
  keywords: ["laugh","lol","haha","joy","giggle","happy","fun"],
  unicode: "😆",
  version: '1.0.0',
  svg: "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 128 128\" width=\"100%\" height=\"100%\" fill=\"none\"><ellipse cx=\"26\" cy=\"74\" rx=\"15\" ry=\"9\" fill=\"#FFA3BA\" fill-opacity=\"0.7\"/><ellipse cx=\"102\" cy=\"74\" rx=\"15\" ry=\"9\" fill=\"#FFA3BA\" fill-opacity=\"0.7\"/><path d=\"M28 32 C36 26 48 26 56 32\" stroke=\"#1E1F24\" stroke-width=\"4.5\" stroke-linecap=\"round\"/><path d=\"M72 32 C80 26 92 26 100 32\" stroke=\"#1E1F24\" stroke-width=\"4.5\" stroke-linecap=\"round\"/><path d=\"M30 52 C36 42 48 42 54 52\" stroke=\"#1E1F24\" stroke-width=\"5\" stroke-linecap=\"round\"/><path d=\"M74 52 C80 42 92 42 98 52\" stroke=\"#1E1F24\" stroke-width=\"5\" stroke-linecap=\"round\"/><path d=\"M38 70 C38 70 42 100 64 100 C86 100 90 70 90 70 Z\" fill=\"#E63946\" stroke=\"#1E1F24\" stroke-width=\"4.5\" stroke-linejoin=\"round\"/><path d=\"M50 94 C56 86 72 86 78 94 C74 99 64 100 50 94 Z\" fill=\"#FF85A1\"/><path d=\"M42 70 Q64 74 86 70\" stroke=\"#FFFFFF\" stroke-width=\"5\" stroke-linecap=\"round\"/></svg>",
  viewBox: '0 0 128 128',
};
