/**
 * Musical Notes Emoji Data
 * Category: symbols
 * Generated by scripts/generate.ts - DO NOT EDIT MANUALLY
 */
import { EmojiData, EmojiCategory } from '../types';

export const MusicNote_DATA: EmojiData = {
  name: 'music-note' as EmojiData['name'],
  label: "Musical Notes",
  category: 'symbols' as EmojiCategory,
  keywords: ["music","note","song","melody","sound","tune","audio"],
  unicode: "🎵",
  version: '1.1.0',
  svg: "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 128 128\" width=\"100%\" height=\"100%\" fill=\"none\"><ellipse cx=\"36\" cy=\"92\" rx=\"14\" ry=\"10\" fill=\"#FF4D6D\" stroke=\"#1E1F24\" stroke-width=\"4.5\" transform=\"rotate(-20 36 92)\"/><ellipse cx=\"88\" cy=\"78\" rx=\"14\" ry=\"10\" fill=\"#FFD166\" stroke=\"#1E1F24\" stroke-width=\"4.5\" transform=\"rotate(-20 88 78)\"/><line x1=\"46\" y1=\"88\" x2=\"46\" y2=\"28\" stroke=\"#1E1F24\" stroke-width=\"5\" stroke-linecap=\"round\"/><line x1=\"98\" y1=\"74\" x2=\"98\" y2=\"14\" stroke=\"#1E1F24\" stroke-width=\"5\" stroke-linecap=\"round\"/><polygon points=\"44,28 100,14 100,24 44,38\" fill=\"#1E1F24\"/><polygon points=\"44,44 100,30 100,38 44,52\" fill=\"#1E1F24\"/><circle cx=\"22\" cy=\"46\" r=\"3.5\" fill=\"#70D6FF\"/><circle cx=\"108\" cy=\"54\" r=\"3.5\" fill=\"#06D6A0\"/></svg>",
  viewBox: '0 0 128 128',
};
