/**
 * Cute Panda Emoji Data
 * Category: animals
 * Generated by scripts/generate.ts - DO NOT EDIT MANUALLY
 */
import { EmojiData, EmojiCategory } from '../types';

export const Panda_DATA: EmojiData = {
  name: 'panda' as EmojiData['name'],
  label: "Cute Panda",
  category: 'animals' as EmojiCategory,
  keywords: ["panda","bear","bamboo","black","white","cute","fluffy"],
  unicode: "🐼",
  version: '1.1.0',
  svg: "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 128 128\" width=\"100%\" height=\"100%\" fill=\"none\"><circle cx=\"34\" cy=\"38\" r=\"16\" fill=\"#1E1F24\"/><circle cx=\"94\" cy=\"38\" r=\"16\" fill=\"#1E1F24\"/><circle cx=\"64\" cy=\"72\" r=\"44\" fill=\"#FFFFFF\" stroke=\"#1E1F24\" stroke-width=\"4.5\"/><ellipse cx=\"44\" cy=\"62\" rx=\"14\" ry=\"12\" fill=\"#1E1F24\" transform=\"rotate(-15 44 62)\"/><circle cx=\"44\" cy=\"60\" r=\"4.5\" fill=\"#FFFFFF\"/><circle cx=\"46\" cy=\"58\" r=\"1.5\" fill=\"#1E1F24\"/><ellipse cx=\"84\" cy=\"62\" rx=\"14\" ry=\"12\" fill=\"#1E1F24\" transform=\"rotate(15 84 62)\"/><circle cx=\"84\" cy=\"60\" r=\"4.5\" fill=\"#FFFFFF\"/><circle cx=\"82\" cy=\"58\" r=\"1.5\" fill=\"#1E1F24\"/><ellipse cx=\"32\" cy=\"80\" rx=\"9\" ry=\"6\" fill=\"#FFA3BA\" fill-opacity=\"0.8\"/><ellipse cx=\"96\" cy=\"80\" rx=\"9\" ry=\"6\" fill=\"#FFA3BA\" fill-opacity=\"0.8\"/><path d=\"M60 76 L68 76 L64 81 Z\" fill=\"#1E1F24\"/><path d=\"M58 84 C62 88 66 88 66 84 C66 88 70 88 74 84\" stroke=\"#1E1F24\" stroke-width=\"3\" stroke-linecap=\"round\"/></svg>",
  viewBox: '0 0 128 128',
};
