/**
 * Party Mascot Emoji Data
 * Category: fun
 * Generated by scripts/generate.ts - DO NOT EDIT MANUALLY
 */
import { EmojiData, EmojiCategory } from '../types';

export const Party_DATA: EmojiData = {
  name: 'party' as EmojiData['name'],
  label: "Party Mascot",
  category: 'fun' as EmojiCategory,
  keywords: ["party","hat","horn","festive","birthday","celebration"],
  unicode: "🥳",
  version: '1.0.0',
  svg: "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 128 128\" width=\"100%\" height=\"100%\" fill=\"none\"><g transform=\"translate(68, 8) rotate(15)\"><polygon points=\"0,0 -20,40 20,40\" fill=\"#4CC9F0\" stroke=\"#1E1F24\" stroke-width=\"3.5\" stroke-linejoin=\"round\"/><path d=\"M-10 20 L10 20\" stroke=\"#FFD166\" stroke-width=\"3.5\"/><path d=\"M-15 30 L15 30\" stroke=\"#FF4D6D\" stroke-width=\"3.5\"/><circle cx=\"0\" cy=\"-2\" r=\"5\" fill=\"#FFB703\" stroke=\"#1E1F24\" stroke-width=\"2.5\"/></g><ellipse cx=\"26\" cy=\"74\" rx=\"14\" ry=\"9\" fill=\"#FFA3BA\" fill-opacity=\"0.7\"/><ellipse cx=\"102\" cy=\"74\" rx=\"14\" ry=\"9\" fill=\"#FFA3BA\" fill-opacity=\"0.7\"/><path d=\"M30 52 C36 44 46 44 52 52\" stroke=\"#1E1F24\" stroke-width=\"4.5\" stroke-linecap=\"round\"/><path d=\"M76 52 C82 44 92 44 98 52\" stroke=\"#1E1F24\" stroke-width=\"4.5\" stroke-linecap=\"round\"/><g transform=\"translate(64, 80)\"><path d=\"M-6 0 L-26 12 C-34 16 -38 10 -34 4 C-30 -2 -14 0 -6 0\" fill=\"#FFB703\" stroke=\"#1E1F24\" stroke-width=\"3.5\" stroke-linejoin=\"round\"/><circle cx=\"-32\" cy=\"8\" r=\"5\" fill=\"#FF4D6D\" stroke=\"#1E1F24\" stroke-width=\"2.5\"/></g><path d=\"M48 80 C54 90 74 90 80 80\" stroke=\"#1E1F24\" stroke-width=\"4.5\" stroke-linecap=\"round\"/><circle cx=\"20\" cy=\"38\" r=\"3.5\" fill=\"#FF4D6D\"/><circle cx=\"106\" cy=\"34\" r=\"3.5\" fill=\"#80B918\"/><polygon points=\"28,24 30,28 34,28 31,31 32,35 28,33 24,35 25,31 22,28 26,28\" fill=\"#FFD166\"/></svg>",
  viewBox: '0 0 128 128',
};
