/**
 * Pizza Slice Emoji Data
 * Category: food
 * Generated by scripts/generate.ts - DO NOT EDIT MANUALLY
 */
import { EmojiData, EmojiCategory } from '../types';

export const Pizza_DATA: EmojiData = {
  name: 'pizza' as EmojiData['name'],
  label: "Pizza Slice",
  category: 'food' as EmojiCategory,
  keywords: ["pizza","slice","cheese","pepperoni","italian","food","fastfood"],
  unicode: "🍕",
  version: '1.1.0',
  svg: "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 128 128\" width=\"100%\" height=\"100%\" fill=\"none\"><path d=\"M28 32 C50 18 78 18 100 32 L64 112 Z\" fill=\"#FFB703\" stroke=\"#1E1F24\" stroke-width=\"4.5\" stroke-linejoin=\"round\"/><path d=\"M26 32 C50 16 78 16 102 32 C96 40 32 40 26 32 Z\" fill=\"#CB997E\" stroke=\"#1E1F24\" stroke-width=\"4\" stroke-linejoin=\"round\"/><path d=\"M32 38 C50 32 78 32 96 38\" stroke=\"#E63946\" stroke-width=\"4\" stroke-linecap=\"round\"/><circle cx=\"50\" cy=\"54\" r=\"8\" fill=\"#D62828\" stroke=\"#1E1F24\" stroke-width=\"2.5\"/><circle cx=\"78\" cy=\"54\" r=\"8\" fill=\"#D62828\" stroke=\"#1E1F24\" stroke-width=\"2.5\"/><circle cx=\"64\" cy=\"78\" r=\"8\" fill=\"#D62828\" stroke=\"#1E1F24\" stroke-width=\"2.5\"/><rect x=\"58\" y=\"44\" width=\"6\" height=\"4\" rx=\"1.5\" fill=\"#52B788\" transform=\"rotate(20 58 44)\"/><rect x=\"74\" y=\"70\" width=\"6\" height=\"4\" rx=\"1.5\" fill=\"#52B788\" transform=\"rotate(-30 74 70)\"/><path d=\"M46 70 C46 80 52 80 52 70\" fill=\"#FFD166\" stroke=\"#1E1F24\" stroke-width=\"2.5\"/></svg>",
  viewBox: '0 0 128 128',
};
