/**
 * Pleading Puppy Eyes Emoji Data
 * Category: emotions
 * Generated by scripts/generate.ts - DO NOT EDIT MANUALLY
 */
import { EmojiData, EmojiCategory } from '../types';

export const Pleading_DATA: EmojiData = {
  name: 'pleading' as EmojiData['name'],
  label: "Pleading Puppy Eyes",
  category: 'emotions' as EmojiCategory,
  keywords: ["pleading","puppy","eyes","beg","please","cute","sparkle"],
  unicode: "🥺",
  version: '1.1.0',
  svg: "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 128 128\" width=\"100%\" height=\"100%\" fill=\"none\"><ellipse cx=\"28\" cy=\"80\" rx=\"15\" ry=\"9\" fill=\"#FFA3BA\" fill-opacity=\"0.7\"/><ellipse cx=\"100\" cy=\"80\" rx=\"15\" ry=\"9\" fill=\"#FFA3BA\" fill-opacity=\"0.7\"/><path d=\"M30 36 C38 42 48 42 54 36\" stroke=\"#1E1F24\" stroke-width=\"4.5\" stroke-linecap=\"round\"/><path d=\"M74 36 C80 42 90 42 98 36\" stroke=\"#1E1F24\" stroke-width=\"4.5\" stroke-linecap=\"round\"/><ellipse cx=\"42\" cy=\"58\" rx=\"16\" ry=\"18\" fill=\"#1E1F24\"/><circle cx=\"48\" cy=\"50\" r=\"7.5\" fill=\"#FFFFFF\"/><circle cx=\"36\" cy=\"66\" r=\"3.8\" fill=\"#FFFFFF\"/><circle cx=\"46\" cy=\"68\" r=\"2.2\" fill=\"#FFFFFF\"/><ellipse cx=\"86\" cy=\"58\" rx=\"16\" ry=\"18\" fill=\"#1E1F24\"/><circle cx=\"92\" cy=\"50\" r=\"7.5\" fill=\"#FFFFFF\"/><circle cx=\"80\" cy=\"66\" r=\"3.8\" fill=\"#FFFFFF\"/><circle cx=\"90\" cy=\"68\" r=\"2.2\" fill=\"#FFFFFF\"/><path d=\"M54 88 C58 84 70 84 74 88\" stroke=\"#1E1F24\" stroke-width=\"4.5\" stroke-linecap=\"round\"/><path d=\"M98 72 C104 76 104 84 98 86 C94 86 92 80 98 72 Z\" fill=\"#70D6FF\" stroke=\"#1E1F24\" stroke-width=\"2.5\"/></svg>",
  viewBox: '0 0 128 128',
};
