/**
 * Pointing Right Emoji Data
 * Category: gestures
 * Generated by scripts/generate.ts - DO NOT EDIT MANUALLY
 */
import { EmojiData, EmojiCategory } from '../types';

export const PointingRight_DATA: EmojiData = {
  name: 'pointing-right' as EmojiData['name'],
  label: "Pointing Right",
  category: 'gestures' as EmojiCategory,
  keywords: ["point","right","finger","index","direction","there"],
  unicode: "👉",
  version: '1.1.0',
  svg: "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 128 128\" width=\"100%\" height=\"100%\" fill=\"none\"><path d=\"M20 54 L20 86 L50 86 C64 86 64 74 64 74 L98 74 C106 74 106 62 98 62 L56 62 C56 54 48 54 38 54 Z\" fill=\"#FFE5D9\" stroke=\"#1E1F24\" stroke-width=\"4.5\" stroke-linejoin=\"round\"/><path d=\"M54 74 C60 74 60 84 54 84\" stroke=\"#1E1F24\" stroke-width=\"3.5\"/><path d=\"M44 74 C50 74 50 84 44 84\" stroke=\"#1E1F24\" stroke-width=\"3.5\"/><path d=\"M38 54 C46 54 48 64 42 68\" stroke=\"#1E1F24\" stroke-width=\"3.5\"/><line x1=\"106\" y1=\"62\" x2=\"116\" y2=\"58\" stroke=\"#FF85A1\" stroke-width=\"3.5\" stroke-linecap=\"round\"/><line x1=\"108\" y1=\"68\" x2=\"120\" y2=\"68\" stroke=\"#FFD166\" stroke-width=\"3.5\" stroke-linecap=\"round\"/><line x1=\"106\" y1=\"74\" x2=\"116\" y2=\"78\" stroke=\"#FF85A1\" stroke-width=\"3.5\" stroke-linecap=\"round\"/></svg>",
  viewBox: '0 0 128 128',
};
