/**
 * Praying / Folded Hands Emoji Data
 * Category: gestures
 * Generated by scripts/generate.ts - DO NOT EDIT MANUALLY
 */
import { EmojiData, EmojiCategory } from '../types';

export const Pray_DATA: EmojiData = {
  name: 'pray' as EmojiData['name'],
  label: "Praying / Folded Hands",
  category: 'gestures' as EmojiCategory,
  keywords: ["pray","folded","hands","thanks","gratitude","please","namaste"],
  unicode: "🙏",
  version: '1.1.0',
  svg: "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 128 128\" width=\"100%\" height=\"100%\" fill=\"none\"><path d=\"M40 108 L58 54 C60 46 64 46 64 54 L64 108 Z\" fill=\"#FFE5D9\" stroke=\"#1E1F24\" stroke-width=\"4\" stroke-linejoin=\"round\"/><path d=\"M88 108 L70 54 C68 46 64 46 64 54 L64 108 Z\" fill=\"#FFE5D9\" stroke=\"#1E1F24\" stroke-width=\"4\" stroke-linejoin=\"round\"/><path d=\"M52 86 C46 80 44 88 50 94\" stroke=\"#1E1F24\" stroke-width=\"3.5\" stroke-linecap=\"round\"/><path d=\"M76 86 C82 80 84 88 78 94\" stroke=\"#1E1F24\" stroke-width=\"3.5\" stroke-linecap=\"round\"/><rect x=\"36\" y=\"104\" width=\"24\" height=\"10\" rx=\"3\" fill=\"#3A86FF\" stroke=\"#1E1F24\" stroke-width=\"3\"/><rect x=\"68\" y=\"104\" width=\"24\" height=\"10\" rx=\"3\" fill=\"#3A86FF\" stroke=\"#1E1F24\" stroke-width=\"3\"/><path d=\"M64 20 L64 32\" stroke=\"#FFD166\" stroke-width=\"3.5\" stroke-linecap=\"round\"/><path d=\"M44 26 L52 36\" stroke=\"#FFD166\" stroke-width=\"3.5\" stroke-linecap=\"round\"/><path d=\"M84 26 L76 36\" stroke=\"#FFD166\" stroke-width=\"3.5\" stroke-linecap=\"round\"/></svg>",
  viewBox: '0 0 128 128',
};
