/**
 * Sick / Puking Emoji Data
 * Category: emotions
 * Generated by scripts/generate.ts - DO NOT EDIT MANUALLY
 */
import { EmojiData, EmojiCategory } from '../types';

export const Puke_DATA: EmojiData = {
  name: 'puke' as EmojiData['name'],
  label: "Sick / Puking",
  category: 'emotions' as EmojiCategory,
  keywords: ["puke","sick","vomit","gross","ill","green","nauseous"],
  unicode: "🤮",
  version: '1.1.0',
  svg: "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 128 128\" width=\"100%\" height=\"100%\" fill=\"none\"><ellipse cx=\"64\" cy=\"46\" rx=\"36\" ry=\"18\" fill=\"#70E000\" fill-opacity=\"0.3\"/><path d=\"M34 50 L48 56 L34 62\" stroke=\"#1E1F24\" stroke-width=\"4.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M94 50 L80 56 L94 62\" stroke=\"#1E1F24\" stroke-width=\"4.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M48 76 C48 76 50 112 64 112 C78 112 80 76 80 76 Z\" fill=\"#70E000\" stroke=\"#1E1F24\" stroke-width=\"4\" stroke-linejoin=\"round\"/><circle cx=\"58\" cy=\"94\" r=\"3\" fill=\"#38B000\"/><circle cx=\"70\" cy=\"100\" r=\"2.5\" fill=\"#38B000\"/><circle cx=\"42\" cy=\"102\" r=\"3.5\" fill=\"#70E000\" stroke=\"#1E1F24\" stroke-width=\"2\"/><circle cx=\"86\" cy=\"104\" r=\"3.5\" fill=\"#70E000\" stroke=\"#1E1F24\" stroke-width=\"2\"/></svg>",
  viewBox: '0 0 128 128',
};
