/**
 * Ramen Bowl Emoji Data
 * Category: food
 * Generated by scripts/generate.ts - DO NOT EDIT MANUALLY
 */
import { EmojiData, EmojiCategory } from '../types';

export const Ramen_DATA: EmojiData = {
  name: 'ramen' as EmojiData['name'],
  label: "Ramen Bowl",
  category: 'food' as EmojiCategory,
  keywords: ["ramen","noodles","soup","bowl","japanese","delicious","egg"],
  unicode: "🍜",
  version: '1.1.0',
  svg: "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 128 128\" width=\"100%\" height=\"100%\" fill=\"none\"><line x1=\"28\" y1=\"20\" x2=\"108\" y2=\"44\" stroke=\"#DDB892\" stroke-width=\"4.5\" stroke-linecap=\"round\"/><line x1=\"30\" y1=\"28\" x2=\"110\" y2=\"52\" stroke=\"#DDB892\" stroke-width=\"4.5\" stroke-linecap=\"round\"/><ellipse cx=\"64\" cy=\"62\" rx=\"42\" ry=\"14\" fill=\"#E76F51\"/><path d=\"M40 58 C46 52 50 64 56 58 C62 52 66 64 72 58\" stroke=\"#FFE49E\" stroke-width=\"4.5\" stroke-linecap=\"round\" fill=\"none\"/><ellipse cx=\"46\" cy=\"60\" rx=\"9\" ry=\"7\" fill=\"#FFFFFF\"/><circle cx=\"46\" cy=\"60\" r=\"4.5\" fill=\"#FB8500\"/><circle cx=\"82\" cy=\"60\" r=\"7\" fill=\"#FFFFFF\"/><path d=\"M80 58 C84 58 84 62 80 62\" stroke=\"#FF5E7E\" stroke-width=\"2\" fill=\"none\"/><path d=\"M22 62 C22 96 40 108 64 108 C88 108 106 96 106 62 Z\" fill=\"#E63946\" stroke=\"#1E1F24\" stroke-width=\"4.5\" stroke-linejoin=\"round\"/><ellipse cx=\"64\" cy=\"62\" rx=\"42\" ry=\"10\" stroke=\"#1E1F24\" stroke-width=\"4.5\" fill=\"none\"/><rect x=\"52\" y=\"106\" width=\"24\" height=\"6\" rx=\"2\" fill=\"#E63946\" stroke=\"#1E1F24\" stroke-width=\"3\"/></svg>",
  viewBox: '0 0 128 128',
};
