/**
 * Launching Rocket Emoji Data
 * Category: objects
 * Generated by scripts/generate.ts - DO NOT EDIT MANUALLY
 */
import { EmojiData, EmojiCategory } from '../types';

export const Rocket_DATA: EmojiData = {
  name: 'rocket' as EmojiData['name'],
  label: "Launching Rocket",
  category: 'objects' as EmojiCategory,
  keywords: ["rocket","launch","space","ship","fast","blastoff","crypto","to-the-moon"],
  unicode: "🚀",
  version: '1.1.0',
  svg: "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 128 128\" width=\"100%\" height=\"100%\" fill=\"none\"><path d=\"M42 86 C32 108 48 116 52 108 C56 120 72 120 76 108 C80 116 96 108 86 86 Z\" fill=\"#FB8500\" stroke=\"#1E1F24\" stroke-width=\"3\" stroke-linejoin=\"round\"/><path d=\"M52 86 C48 100 58 106 64 98 C70 106 80 100 76 86 Z\" fill=\"#FFD166\"/><path d=\"M40 70 L24 88 L42 88 Z\" fill=\"#E63946\" stroke=\"#1E1F24\" stroke-width=\"4\" stroke-linejoin=\"round\"/><path d=\"M88 70 L104 88 L86 88 Z\" fill=\"#E63946\" stroke=\"#1E1F24\" stroke-width=\"4\" stroke-linejoin=\"round\"/><path d=\"M64 16 C48 36 44 68 44 88 L84 88 C84 68 80 36 64 16 Z\" fill=\"#F8F9FA\" stroke=\"#1E1F24\" stroke-width=\"4.5\" stroke-linejoin=\"round\"/><path d=\"M64 16 C56 26 52 38 52 42 L76 42 C76 38 72 26 64 16 Z\" fill=\"#E63946\" stroke=\"#1E1F24\" stroke-width=\"3.5\" stroke-linejoin=\"round\"/><circle cx=\"64\" cy=\"60\" r=\"11\" fill=\"#70D6FF\" stroke=\"#1E1F24\" stroke-width=\"3.5\"/><circle cx=\"67\" cy=\"57\" r=\"3.5\" fill=\"#FFFFFF\"/></svg>",
  viewBox: '0 0 128 128',
};
