/**
 * Sad Pout Emoji Data
 * Category: emotions
 * Generated by scripts/generate.ts - DO NOT EDIT MANUALLY
 */
import { EmojiData, EmojiCategory } from '../types';

export const Sad_DATA: EmojiData = {
  name: 'sad' as EmojiData['name'],
  label: "Sad Pout",
  category: 'emotions' as EmojiCategory,
  keywords: ["sad","pout","down","unhappy","sorrow","frown"],
  unicode: "🥺",
  version: '1.0.0',
  svg: "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 128 128\" width=\"100%\" height=\"100%\" fill=\"none\"><ellipse cx=\"26\" cy=\"74\" rx=\"14\" ry=\"9\" fill=\"#FFA3BA\" fill-opacity=\"0.65\"/><ellipse cx=\"102\" cy=\"74\" rx=\"14\" ry=\"9\" fill=\"#FFA3BA\" fill-opacity=\"0.65\"/><path d=\"M30 40 C38 32 48 30 56 36\" stroke=\"#1E1F24\" stroke-width=\"4.5\" stroke-linecap=\"round\"/><path d=\"M72 36 C80 30 90 32 98 40\" stroke=\"#1E1F24\" stroke-width=\"4.5\" stroke-linecap=\"round\"/><ellipse cx=\"44\" cy=\"54\" rx=\"12\" ry=\"14\" fill=\"#1E1F24\"/><circle cx=\"41\" cy=\"48\" r=\"4.5\" fill=\"#FFFFFF\"/><circle cx=\"49\" cy=\"58\" r=\"2.5\" fill=\"#FFFFFF\"/><path d=\"M36 60 C40 64 48 64 52 60\" stroke=\"#70D6FF\" stroke-width=\"2.5\" stroke-linecap=\"round\"/><ellipse cx=\"84\" cy=\"54\" rx=\"12\" ry=\"14\" fill=\"#1E1F24\"/><circle cx=\"81\" cy=\"48\" r=\"4.5\" fill=\"#FFFFFF\"/><circle cx=\"89\" cy=\"58\" r=\"2.5\" fill=\"#FFFFFF\"/><path d=\"M76 60 C80 64 88 64 92 60\" stroke=\"#70D6FF\" stroke-width=\"2.5\" stroke-linecap=\"round\"/><path d=\"M48 88 C54 78 74 78 80 88\" stroke=\"#1E1F24\" stroke-width=\"4.5\" stroke-linecap=\"round\"/><path d=\"M60 94 Q64 92 68 94\" stroke=\"#1E1F24\" stroke-width=\"2.5\" stroke-linecap=\"round\"/></svg>",
  viewBox: '0 0 128 128',
};
