/**
 * Sleepy / Zzz Emoji Data
 * Category: faces
 * Generated by scripts/generate.ts - DO NOT EDIT MANUALLY
 */
import { EmojiData, EmojiCategory } from '../types';

export const Sleepy_DATA: EmojiData = {
  name: 'sleepy' as EmojiData['name'],
  label: "Sleepy / Zzz",
  category: 'faces' as EmojiCategory,
  keywords: ["sleepy","tired","sleep","zzz","bedtime","nap","bubble"],
  unicode: "😴",
  version: '1.0.0',
  svg: "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 128 128\" width=\"100%\" height=\"100%\" fill=\"none\"><ellipse cx=\"26\" cy=\"74\" rx=\"14\" ry=\"8\" fill=\"#FFA3BA\" fill-opacity=\"0.6\"/><ellipse cx=\"102\" cy=\"74\" rx=\"14\" ry=\"8\" fill=\"#FFA3BA\" fill-opacity=\"0.6\"/><path d=\"M30 38 C36 34 46 36 52 40\" stroke=\"#1E1F24\" stroke-width=\"4.5\" stroke-linecap=\"round\"/><path d=\"M76 40 C82 36 92 34 98 38\" stroke=\"#1E1F24\" stroke-width=\"4.5\" stroke-linecap=\"round\"/><path d=\"M32 54 C38 58 46 58 52 54\" stroke=\"#1E1F24\" stroke-width=\"4.5\" stroke-linecap=\"round\"/><path d=\"M76 54 C82 58 90 58 96 54\" stroke=\"#1E1F24\" stroke-width=\"4.5\" stroke-linecap=\"round\"/><circle cx=\"70\" cy=\"70\" r=\"14\" fill=\"#70D6FF\" fill-opacity=\"0.6\" stroke=\"#1E1F24\" stroke-width=\"3\"/><circle cx=\"66\" cy=\"66\" r=\"4\" fill=\"#FFFFFF\" fill-opacity=\"0.8\"/><circle cx=\"74\" cy=\"74\" r=\"2\" fill=\"#FFFFFF\" fill-opacity=\"0.8\"/><path d=\"M48 80 C54 84 62 84 66 80\" stroke=\"#1E1F24\" stroke-width=\"4.5\" stroke-linecap=\"round\"/><path d=\"M96 22 L106 22 L96 32 L106 32\" stroke=\"#4CC9F0\" stroke-width=\"3.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M108 10 L114 10 L108 16 L114 16\" stroke=\"#4CC9F0\" stroke-width=\"2.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>",
  viewBox: '0 0 128 128',
};
