/**
 * Smug / Heh Emoji Data
 * Category: faces
 * Generated by scripts/generate.ts - DO NOT EDIT MANUALLY
 */
import { EmojiData, EmojiCategory } from '../types';

export const Smug_DATA: EmojiData = {
  name: 'smug' as EmojiData['name'],
  label: "Smug / Heh",
  category: 'faces' as EmojiCategory,
  keywords: ["smug","sly","clever","heh","confident","grin"],
  unicode: "😏",
  version: '1.0.0',
  svg: "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 128 128\" width=\"100%\" height=\"100%\" fill=\"none\"><ellipse cx=\"26\" cy=\"74\" rx=\"14\" ry=\"8\" fill=\"#FFA3BA\" fill-opacity=\"0.6\"/><ellipse cx=\"102\" cy=\"74\" rx=\"14\" ry=\"8\" fill=\"#FFA3BA\" fill-opacity=\"0.6\"/><path d=\"M28 28 C36 22 48 24 54 30\" stroke=\"#1E1F24\" stroke-width=\"4.5\" stroke-linecap=\"round\"/><path d=\"M74 34 C80 34 92 32 98 36\" stroke=\"#1E1F24\" stroke-width=\"4.5\" stroke-linecap=\"round\"/><path d=\"M32 52 C36 46 48 46 54 52\" stroke=\"#1E1F24\" stroke-width=\"4.5\" stroke-linecap=\"round\"/><ellipse cx=\"44\" cy=\"53\" rx=\"6\" ry=\"6\" fill=\"#1E1F24\"/><circle cx=\"46\" cy=\"51\" r=\"2\" fill=\"#FFFFFF\"/><path d=\"M34 54 Q44 58 52 54\" stroke=\"#1E1F24\" stroke-width=\"2.5\"/><path d=\"M74 52 C80 46 92 46 96 52\" stroke=\"#1E1F24\" stroke-width=\"4.5\" stroke-linecap=\"round\"/><ellipse cx=\"86\" cy=\"53\" rx=\"6\" ry=\"6\" fill=\"#1E1F24\"/><circle cx=\"88\" cy=\"51\" r=\"2\" fill=\"#FFFFFF\"/><path d=\"M76 54 Q86 58 94 54\" stroke=\"#1E1F24\" stroke-width=\"2.5\"/><path d=\"M48 80 C60 80 82 86 86 68\" stroke=\"#1E1F24\" stroke-width=\"4.5\" stroke-linecap=\"round\"/><path d=\"M84 68 C86 66 90 70 86 74\" stroke=\"#1E1F24\" stroke-width=\"3\" stroke-linecap=\"round\"/></svg>",
  viewBox: '0 0 128 128',
};
