/**
 * Magic Sparkles Emoji Data
 * Category: symbols
 * Generated by scripts/generate.ts - DO NOT EDIT MANUALLY
 */
import { EmojiData, EmojiCategory } from '../types';

export const Sparkles_DATA: EmojiData = {
  name: 'sparkles' as EmojiData['name'],
  label: "Magic Sparkles",
  category: 'symbols' as EmojiCategory,
  keywords: ["sparkles","magic","glitter","shine","stars","sparkle","clean"],
  unicode: "✨",
  version: '1.1.0',
  svg: "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 128 128\" width=\"100%\" height=\"100%\" fill=\"none\"><path d=\"M64 16 C64 42 76 54 102 54 C76 54 64 66 64 92 C64 66 52 54 26 54 C52 54 64 42 64 16 Z\" fill=\"#FFD166\" stroke=\"#1E1F24\" stroke-width=\"4\" stroke-linejoin=\"round\"/><path d=\"M28 22 C28 34 34 40 46 40 C34 40 28 46 28 58 C28 46 22 40 10 40 C22 40 28 34 28 22 Z\" fill=\"#70D6FF\" stroke=\"#1E1F24\" stroke-width=\"3\" stroke-linejoin=\"round\"/><path d=\"M96 74 C96 86 102 92 114 92 C102 92 96 98 96 110 C96 98 90 92 78 92 C90 92 96 86 96 74 Z\" fill=\"#FF758F\" stroke=\"#1E1F24\" stroke-width=\"3\" stroke-linejoin=\"round\"/></svg>",
  viewBox: '0 0 128 128',
};
