/**
 * Golden Star Emoji Data
 * Category: symbols
 * Generated by scripts/generate.ts - DO NOT EDIT MANUALLY
 */
import { EmojiData, EmojiCategory } from '../types';

export const Starry_DATA: EmojiData = {
  name: 'starry' as EmojiData['name'],
  label: "Golden Star",
  category: 'symbols' as EmojiCategory,
  keywords: ["star","sparkle","gold","favorite","shine","badge"],
  unicode: "⭐",
  version: '1.0.0',
  svg: "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 128 128\" width=\"100%\" height=\"100%\" fill=\"none\"><g transform=\"translate(64, 64) scale(1.1)\"><path d=\"M0,-46 L13,-14 L46,-10 L22,12 L29,46 L0,28 L-29,46 L-22,12 L-46,-10 L-13,-14 Z\" fill=\"#FFB703\" stroke=\"#1E1F24\" stroke-width=\"4.5\" stroke-linejoin=\"round\"/><ellipse cx=\"-11\" cy=\"2\" rx=\"3.5\" ry=\"4.5\" fill=\"#1E1F24\"/><circle cx=\"-10\" cy=\"0\" r=\"1.5\" fill=\"#FFFFFF\"/><ellipse cx=\"11\" cy=\"2\" rx=\"3.5\" ry=\"4.5\" fill=\"#1E1F24\"/><circle cx=\"12\" cy=\"0\" r=\"1.5\" fill=\"#FFFFFF\"/><ellipse cx=\"-18\" cy=\"8\" rx=\"4\" ry=\"2.5\" fill=\"#FF758F\" fill-opacity=\"0.8\"/><ellipse cx=\"18\" cy=\"8\" rx=\"4\" ry=\"2.5\" fill=\"#FF758F\" fill-opacity=\"0.8\"/><path d=\"M-6 10 C-3 16 3 16 6 10\" stroke=\"#1E1F24\" stroke-width=\"3\" stroke-linecap=\"round\"/></g><circle cx=\"20\" cy=\"26\" r=\"3.5\" fill=\"#FFD166\"/><circle cx=\"108\" cy=\"30\" r=\"3\" fill=\"#FFD166\"/><polygon points=\"104,96 107,102 113,102 108,105 110,111 104,107 98,111 100,105 95,102 101,102\" fill=\"#FFD166\"/></svg>",
  viewBox: '0 0 128 128',
};
