/**
 * Smiling Sun Emoji Data
 * Category: symbols
 * Generated by scripts/generate.ts - DO NOT EDIT MANUALLY
 */
import { EmojiData, EmojiCategory } from '../types';

export const Sun_DATA: EmojiData = {
  name: 'sun' as EmojiData['name'],
  label: "Smiling Sun",
  category: 'symbols' as EmojiCategory,
  keywords: ["sun","sunny","sunshine","summer","weather","warm","bright"],
  unicode: "☀️",
  version: '1.1.0',
  svg: "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 128 128\" width=\"100%\" height=\"100%\" fill=\"none\"><path d=\"M64 12 L64 24\" stroke=\"#FFB703\" stroke-width=\"6\" stroke-linecap=\"round\"/><path d=\"M64 104 L64 116\" stroke=\"#FFB703\" stroke-width=\"6\" stroke-linecap=\"round\"/><path d=\"M12 64 L24 64\" stroke=\"#FFB703\" stroke-width=\"6\" stroke-linecap=\"round\"/><path d=\"M104 64 L116 64\" stroke=\"#FFB703\" stroke-width=\"6\" stroke-linecap=\"round\"/><path d=\"M28 28 L36 36\" stroke=\"#FFB703\" stroke-width=\"6\" stroke-linecap=\"round\"/><path d=\"M92 92 L100 100\" stroke=\"#FFB703\" stroke-width=\"6\" stroke-linecap=\"round\"/><path d=\"M28 100 L36 92\" stroke=\"#FFB703\" stroke-width=\"6\" stroke-linecap=\"round\"/><path d=\"M92 36 L100 28\" stroke=\"#FFB703\" stroke-width=\"6\" stroke-linecap=\"round\"/><circle cx=\"64\" cy=\"64\" r=\"36\" fill=\"#FFD166\" stroke=\"#1E1F24\" stroke-width=\"4.5\"/><ellipse cx=\"44\" cy=\"70\" rx=\"7\" ry=\"4.5\" fill=\"#FFA3BA\" fill-opacity=\"0.85\"/><ellipse cx=\"84\" cy=\"70\" rx=\"7\" ry=\"4.5\" fill=\"#FFA3BA\" fill-opacity=\"0.85\"/><circle cx=\"50\" cy=\"58\" r=\"5\" fill=\"#1E1F24\"/><circle cx=\"52\" cy=\"56\" r=\"2\" fill=\"#FFFFFF\"/><circle cx=\"78\" cy=\"58\" r=\"5\" fill=\"#1E1F24\"/><circle cx=\"80\" cy=\"56\" r=\"2\" fill=\"#FFFFFF\"/><path d=\"M56 70 C60 76 68 76 72 70\" stroke=\"#1E1F24\" stroke-width=\"3.5\" stroke-linecap=\"round\"/></svg>",
  viewBox: '0 0 128 128',
};
