/**
 * Surprised Emoji Data
 * Category: reactions
 * Generated by scripts/generate.ts - DO NOT EDIT MANUALLY
 */
import { EmojiData, EmojiCategory } from '../types';

export const Surprised_DATA: EmojiData = {
  name: 'surprised' as EmojiData['name'],
  label: "Surprised",
  category: 'reactions' as EmojiCategory,
  keywords: ["surprised","gasp","shock","wow","omg","eyes"],
  unicode: "😮",
  version: '1.0.0',
  svg: "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 128 128\" width=\"100%\" height=\"100%\" fill=\"none\"><ellipse cx=\"22\" cy=\"74\" rx=\"14\" ry=\"9\" fill=\"#FFA3BA\" fill-opacity=\"0.6\"/><ellipse cx=\"106\" cy=\"74\" rx=\"14\" ry=\"9\" fill=\"#FFA3BA\" fill-opacity=\"0.6\"/><path d=\"M26 24 C34 18 48 18 56 24\" stroke=\"#1E1F24\" stroke-width=\"4.5\" stroke-linecap=\"round\"/><path d=\"M72 24 C80 18 94 18 102 24\" stroke=\"#1E1F24\" stroke-width=\"4.5\" stroke-linecap=\"round\"/><circle cx=\"40\" cy=\"48\" r=\"14\" fill=\"#FFFFFF\" stroke=\"#1E1F24\" stroke-width=\"4\"/><circle cx=\"40\" cy=\"48\" r=\"5.5\" fill=\"#1E1F24\"/><circle cx=\"42\" cy=\"46\" r=\"2\" fill=\"#FFFFFF\"/><circle cx=\"88\" cy=\"48\" r=\"14\" fill=\"#FFFFFF\" stroke=\"#1E1F24\" stroke-width=\"4\"/><circle cx=\"88\" cy=\"48\" r=\"5.5\" fill=\"#1E1F24\"/><circle cx=\"90\" cy=\"46\" r=\"2\" fill=\"#FFFFFF\"/><path d=\"M18 42 L22 44\" stroke=\"#1E1F24\" stroke-width=\"3\" stroke-linecap=\"round\"/><path d=\"M106 44 L110 42\" stroke=\"#1E1F24\" stroke-width=\"3\" stroke-linecap=\"round\"/><ellipse cx=\"64\" cy=\"84\" rx=\"11\" ry=\"15\" fill=\"#FF5E7E\" stroke=\"#1E1F24\" stroke-width=\"4.5\"/><path d=\"M58 88 C60 92 68 92 70 88\" stroke=\"#FF85A1\" stroke-width=\"3\" stroke-linecap=\"round\"/></svg>",
  viewBox: '0 0 128 128',
};
