/**
 * Winking Emoji Data
 * Category: faces
 * Generated by scripts/generate.ts - DO NOT EDIT MANUALLY
 */
import { EmojiData, EmojiCategory } from '../types';

export const Wink_DATA: EmojiData = {
  name: 'wink' as EmojiData['name'],
  label: "Winking",
  category: 'faces' as EmojiCategory,
  keywords: ["wink","playful","cheeky","flirt","joke"],
  unicode: "😉",
  version: '1.0.0',
  svg: "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 128 128\" width=\"100%\" height=\"100%\" fill=\"none\"><ellipse cx=\"28\" cy=\"74\" rx=\"14\" ry=\"9\" fill=\"#FFA3BA\" fill-opacity=\"0.65\"/><ellipse cx=\"100\" cy=\"74\" rx=\"14\" ry=\"9\" fill=\"#FFA3BA\" fill-opacity=\"0.65\"/><path d=\"M30 34 C36 28 48 30 54 36\" stroke=\"#1E1F24\" stroke-width=\"4.5\" stroke-linecap=\"round\"/><path d=\"M74 36 C80 30 92 28 98 34\" stroke=\"#1E1F24\" stroke-width=\"4.5\" stroke-linecap=\"round\"/><ellipse cx=\"42\" cy=\"54\" rx=\"9\" ry=\"11\" fill=\"#1E1F24\"/><circle cx=\"45\" cy=\"51\" r=\"3.5\" fill=\"#FFFFFF\"/><circle cx=\"39\" cy=\"57\" r=\"1.8\" fill=\"#FFFFFF\"/><path d=\"M74 54 Q86 64 98 54\" stroke=\"#1E1F24\" stroke-width=\"5\" stroke-linecap=\"round\"/><path d=\"M96 52 L103 48\" stroke=\"#1E1F24\" stroke-width=\"3.5\" stroke-linecap=\"round\"/><circle cx=\"64\" cy=\"66\" r=\"2.2\" fill=\"#1E1F24\"/><path d=\"M46 76 Q64 92 82 76\" stroke=\"#1E1F24\" stroke-width=\"4.5\" stroke-linecap=\"round\"/><path d=\"M66 82 C66 94 78 94 78 82\" fill=\"#FF758F\" stroke=\"#1E1F24\" stroke-width=\"3\"/></svg>",
  viewBox: '0 0 128 128',
};
