/**
 * Generated by scripts/generate.ts - DO NOT EDIT MANUALLY
 * Each emoji is in its own module for optimal tree-shaking.
 */
import { EmojiData, EmojiName } from './types';

import { Angel_DATA } from './emojis/angel';
import { Angry_DATA } from './emojis/angry';
import { Applause_DATA } from './emojis/applause';
import { Avocado_DATA } from './emojis/avocado';
import { Balloon_DATA } from './emojis/balloon';
import { Bear_DATA } from './emojis/bear';
import { Boba_DATA } from './emojis/boba';
import { Bunny_DATA } from './emojis/bunny';
import { Cake_DATA } from './emojis/cake';
import { CatCry_DATA } from './emojis/cat-cry';
import { CatHappy_DATA } from './emojis/cat-happy';
import { CatLove_DATA } from './emojis/cat-love';
import { Celebrate_DATA } from './emojis/celebrate';
import { CherryBlossom_DATA } from './emojis/cherry-blossom';
import { Clown_DATA } from './emojis/clown';
import { Coffee_DATA } from './emojis/coffee';
import { Confused_DATA } from './emojis/confused';
import { Cool_DATA } from './emojis/cool';
import { Cry_DATA } from './emojis/cry';
import { CutePoop_DATA } from './emojis/cute-poop';
import { Devil_DATA } from './emojis/devil';
import { Diamond_DATA } from './emojis/diamond';
import { Dizzy_DATA } from './emojis/dizzy';
import { DogPuppy_DATA } from './emojis/dog-puppy';
import { Drool_DATA } from './emojis/drool';
import { Duck_DATA } from './emojis/duck';
import { Excited_DATA } from './emojis/excited';
import { FingersCrossed_DATA } from './emojis/fingers-crossed';
import { Fire_DATA } from './emojis/fire';
import { FistBump_DATA } from './emojis/fist-bump';
import { FrogCoffee_DATA } from './emojis/frog-coffee';
import { FrogCry_DATA } from './emojis/frog-cry';
import { FrogDance_DATA } from './emojis/frog-dance';
import { FrogExhausted_DATA } from './emojis/frog-exhausted';
import { FrogGood_DATA } from './emojis/frog-good';
import { FrogGreat_DATA } from './emojis/frog-great';
import { FrogHappy_DATA } from './emojis/frog-happy';
import { FrogLove_DATA } from './emojis/frog-love';
import { FrogLow_DATA } from './emojis/frog-low';
import { FrogNatural_DATA } from './emojis/frog-natural';
import { Ghost_DATA } from './emojis/ghost';
import { Gift_DATA } from './emojis/gift';
import { Handshake_DATA } from './emojis/handshake';
import { Happy_DATA } from './emojis/happy';
import { HeartHands_DATA } from './emojis/heart-hands';
import { Heart_DATA } from './emojis/heart';
import { Hundred_DATA } from './emojis/hundred';
import { IceCream_DATA } from './emojis/ice-cream';
import { Laugh_DATA } from './emojis/laugh';
import { Love_DATA } from './emojis/love';
import { MindBlown_DATA } from './emojis/mind-blown';
import { MoneyFace_DATA } from './emojis/money-face';
import { Moon_DATA } from './emojis/moon';
import { MusicNote_DATA } from './emojis/music-note';
import { Panda_DATA } from './emojis/panda';
import { Party_DATA } from './emojis/party';
import { Peace_DATA } from './emojis/peace';
import { Piggy_DATA } from './emojis/piggy';
import { Pizza_DATA } from './emojis/pizza';
import { Pleading_DATA } from './emojis/pleading';
import { PointingRight_DATA } from './emojis/pointing-right';
import { Pray_DATA } from './emojis/pray';
import { Puke_DATA } from './emojis/puke';
import { Rainbow_DATA } from './emojis/rainbow';
import { Ramen_DATA } from './emojis/ramen';
import { Rocket_DATA } from './emojis/rocket';
import { RollingEyes_DATA } from './emojis/rolling-eyes';
import { Sad_DATA } from './emojis/sad';
import { Scream_DATA } from './emojis/scream';
import { Shy_DATA } from './emojis/shy';
import { Skull_DATA } from './emojis/skull';
import { Sleepy_DATA } from './emojis/sleepy';
import { Smug_DATA } from './emojis/smug';
import { Sparkles_DATA } from './emojis/sparkles';
import { Starry_DATA } from './emojis/starry';
import { Sun_DATA } from './emojis/sun';
import { Surprised_DATA } from './emojis/surprised';
import { SweatSmile_DATA } from './emojis/sweat-smile';
import { Thinking_DATA } from './emojis/thinking';
import { ThumbsDown_DATA } from './emojis/thumbs-down';
import { ThumbsUp_DATA } from './emojis/thumbs-up';
import { Wave_DATA } from './emojis/wave';
import { Wink_DATA } from './emojis/wink';
import { Yawn_DATA } from './emojis/yawn';

export const EMOJI_REGISTRY: Record<EmojiName, EmojiData> = {
  'angel': Angel_DATA,
  'angry': Angry_DATA,
  'applause': Applause_DATA,
  'avocado': Avocado_DATA,
  'balloon': Balloon_DATA,
  'bear': Bear_DATA,
  'boba': Boba_DATA,
  'bunny': Bunny_DATA,
  'cake': Cake_DATA,
  'cat-cry': CatCry_DATA,
  'cat-happy': CatHappy_DATA,
  'cat-love': CatLove_DATA,
  'celebrate': Celebrate_DATA,
  'cherry-blossom': CherryBlossom_DATA,
  'clown': Clown_DATA,
  'coffee': Coffee_DATA,
  'confused': Confused_DATA,
  'cool': Cool_DATA,
  'cry': Cry_DATA,
  'cute-poop': CutePoop_DATA,
  'devil': Devil_DATA,
  'diamond': Diamond_DATA,
  'dizzy': Dizzy_DATA,
  'dog-puppy': DogPuppy_DATA,
  'drool': Drool_DATA,
  'duck': Duck_DATA,
  'excited': Excited_DATA,
  'fingers-crossed': FingersCrossed_DATA,
  'fire': Fire_DATA,
  'fist-bump': FistBump_DATA,
  'frog-coffee': FrogCoffee_DATA,
  'frog-cry': FrogCry_DATA,
  'frog-dance': FrogDance_DATA,
  'frog-exhausted': FrogExhausted_DATA,
  'frog-good': FrogGood_DATA,
  'frog-great': FrogGreat_DATA,
  'frog-happy': FrogHappy_DATA,
  'frog-love': FrogLove_DATA,
  'frog-low': FrogLow_DATA,
  'frog-natural': FrogNatural_DATA,
  'ghost': Ghost_DATA,
  'gift': Gift_DATA,
  'handshake': Handshake_DATA,
  'happy': Happy_DATA,
  'heart-hands': HeartHands_DATA,
  'heart': Heart_DATA,
  'hundred': Hundred_DATA,
  'ice-cream': IceCream_DATA,
  'laugh': Laugh_DATA,
  'love': Love_DATA,
  'mind-blown': MindBlown_DATA,
  'money-face': MoneyFace_DATA,
  'moon': Moon_DATA,
  'music-note': MusicNote_DATA,
  'panda': Panda_DATA,
  'party': Party_DATA,
  'peace': Peace_DATA,
  'piggy': Piggy_DATA,
  'pizza': Pizza_DATA,
  'pleading': Pleading_DATA,
  'pointing-right': PointingRight_DATA,
  'pray': Pray_DATA,
  'puke': Puke_DATA,
  'rainbow': Rainbow_DATA,
  'ramen': Ramen_DATA,
  'rocket': Rocket_DATA,
  'rolling-eyes': RollingEyes_DATA,
  'sad': Sad_DATA,
  'scream': Scream_DATA,
  'shy': Shy_DATA,
  'skull': Skull_DATA,
  'sleepy': Sleepy_DATA,
  'smug': Smug_DATA,
  'sparkles': Sparkles_DATA,
  'starry': Starry_DATA,
  'sun': Sun_DATA,
  'surprised': Surprised_DATA,
  'sweat-smile': SweatSmile_DATA,
  'thinking': Thinking_DATA,
  'thumbs-down': ThumbsDown_DATA,
  'thumbs-up': ThumbsUp_DATA,
  'wave': Wave_DATA,
  'wink': Wink_DATA,
  'yawn': Yawn_DATA,
};

export const EMOJI_LIST: EmojiData[] = Object.values(EMOJI_REGISTRY);

export const EMOJI_NAMES: EmojiName[] = Object.keys(EMOJI_REGISTRY) as EmojiName[];
