/**
 * Generated by scripts/generate.ts - DO NOT EDIT MANUALLY
 * Source of truth: packages/assets/svg & metadata/emojis.json
 */

export type EmojiName =
  | 'angel'
  | 'angry'
  | 'applause'
  | 'avocado'
  | 'balloon'
  | 'bear'
  | 'boba'
  | 'bunny'
  | 'cake'
  | 'cat-cry'
  | 'cat-happy'
  | 'cat-love'
  | 'celebrate'
  | 'cherry-blossom'
  | 'clown'
  | 'coffee'
  | 'confused'
  | 'cool'
  | 'cry'
  | 'cute-poop'
  | 'devil'
  | 'diamond'
  | 'dizzy'
  | 'dog-puppy'
  | 'drool'
  | 'duck'
  | 'excited'
  | 'fingers-crossed'
  | 'fire'
  | 'fist-bump'
  | 'frog-coffee'
  | 'frog-cry'
  | 'frog-dance'
  | 'frog-happy'
  | 'frog-love'
  | 'ghost'
  | 'gift'
  | 'handshake'
  | 'happy'
  | 'heart-hands'
  | 'heart'
  | 'hundred'
  | 'ice-cream'
  | 'laugh'
  | 'love'
  | 'mind-blown'
  | 'money-face'
  | 'moon'
  | 'music-note'
  | 'panda'
  | 'party'
  | 'peace'
  | 'piggy'
  | 'pizza'
  | 'pleading'
  | 'pointing-right'
  | 'pray'
  | 'puke'
  | 'rainbow'
  | 'ramen'
  | 'rocket'
  | 'rolling-eyes'
  | 'sad'
  | 'scream'
  | 'shy'
  | 'skull'
  | 'sleepy'
  | 'smug'
  | 'sparkles'
  | 'starry'
  | 'sun'
  | 'surprised'
  | 'sweat-smile'
  | 'thinking'
  | 'thumbs-down'
  | 'thumbs-up'
  | 'wave'
  | 'wink'
  | 'yawn';

export type EmojiCategory =
  | 'faces'
  | 'emotions'
  | 'reactions'
  | 'people'
  | 'gestures'
  | 'love'
  | 'fun'
  | 'objects'
  | 'animals'
  | 'food'
  | 'symbols'
  | 'miscellaneous';

export interface EmojiMetadata {
  name: EmojiName;
  label: string;
  category: EmojiCategory;
  keywords: string[];
  unicode?: string;
  version: string;
}

export interface EmojiData extends EmojiMetadata {
  svg: string;
  viewBox: string;
}

export interface SearchOptions {
  category?: EmojiCategory;
  limit?: number;
  exact?: boolean;
}

export interface SvgRenderOptions {
  size?: number | string;
  width?: number | string;
  height?: number | string;
  className?: string;
  ariaLabel?: string;
  ariaHidden?: boolean;
  title?: string;
  style?: Record<string, string | number> | string;
}

export interface CreateEmojiOptions extends SvgRenderOptions {
  onClick?: (event: MouseEvent) => void;
}
