/**
 * Generated by scripts/generate.ts - DO NOT EDIT MANUALLY
 * Individual tree-shakeable React emoji components
 */
import React, { forwardRef } from 'react';
import { Emoji } from './Emoji';
import { IndividualEmojiProps } from './types';

/**
 * Innocent Angel Emoji Component
 * Category: faces
 */
export const Angel = forwardRef<SVGSVGElement, IndividualEmojiProps>((props, ref) => {
  return <Emoji name="angel" ref={ref} {...props} />;
});
Angel.displayName = 'Angel';

/**
 * Angry Steam Emoji Component
 * Category: emotions
 */
export const Angry = forwardRef<SVGSVGElement, IndividualEmojiProps>((props, ref) => {
  return <Emoji name="angry" ref={ref} {...props} />;
});
Angry.displayName = 'Angry';

/**
 * Clapping Applause Emoji Component
 * Category: gestures
 */
export const Applause = forwardRef<SVGSVGElement, IndividualEmojiProps>((props, ref) => {
  return <Emoji name="applause" ref={ref} {...props} />;
});
Applause.displayName = 'Applause';

/**
 * Cute Avocado Emoji Component
 * Category: food
 */
export const Avocado = forwardRef<SVGSVGElement, IndividualEmojiProps>((props, ref) => {
  return <Emoji name="avocado" ref={ref} {...props} />;
});
Avocado.displayName = 'Avocado';

/**
 * Party Balloon Emoji Component
 * Category: fun
 */
export const Balloon = forwardRef<SVGSVGElement, IndividualEmojiProps>((props, ref) => {
  return <Emoji name="balloon" ref={ref} {...props} />;
});
Balloon.displayName = 'Balloon';

/**
 * Teddy Bear Emoji Component
 * Category: animals
 */
export const Bear = forwardRef<SVGSVGElement, IndividualEmojiProps>((props, ref) => {
  return <Emoji name="bear" ref={ref} {...props} />;
});
Bear.displayName = 'Bear';

/**
 * Boba Bubble Tea Emoji Component
 * Category: food
 */
export const Boba = forwardRef<SVGSVGElement, IndividualEmojiProps>((props, ref) => {
  return <Emoji name="boba" ref={ref} {...props} />;
});
Boba.displayName = 'Boba';

/**
 * Cute Bunny Emoji Component
 * Category: animals
 */
export const Bunny = forwardRef<SVGSVGElement, IndividualEmojiProps>((props, ref) => {
  return <Emoji name="bunny" ref={ref} {...props} />;
});
Bunny.displayName = 'Bunny';

/**
 * Birthday Cake Emoji Component
 * Category: food
 */
export const Cake = forwardRef<SVGSVGElement, IndividualEmojiProps>((props, ref) => {
  return <Emoji name="cake" ref={ref} {...props} />;
});
Cake.displayName = 'Cake';

/**
 * Crying Cat Emoji Component
 * Category: animals
 */
export const CatCry = forwardRef<SVGSVGElement, IndividualEmojiProps>((props, ref) => {
  return <Emoji name="cat-cry" ref={ref} {...props} />;
});
CatCry.displayName = 'CatCry';

/**
 * Happy Cat Emoji Component
 * Category: animals
 */
export const CatHappy = forwardRef<SVGSVGElement, IndividualEmojiProps>((props, ref) => {
  return <Emoji name="cat-happy" ref={ref} {...props} />;
});
CatHappy.displayName = 'CatHappy';

/**
 * Love Cat Emoji Component
 * Category: animals
 */
export const CatLove = forwardRef<SVGSVGElement, IndividualEmojiProps>((props, ref) => {
  return <Emoji name="cat-love" ref={ref} {...props} />;
});
CatLove.displayName = 'CatLove';

/**
 * Party Popper Emoji Component
 * Category: fun
 */
export const Celebrate = forwardRef<SVGSVGElement, IndividualEmojiProps>((props, ref) => {
  return <Emoji name="celebrate" ref={ref} {...props} />;
});
Celebrate.displayName = 'Celebrate';

/**
 * Cherry Blossom Sakura Emoji Component
 * Category: symbols
 */
export const CherryBlossom = forwardRef<SVGSVGElement, IndividualEmojiProps>((props, ref) => {
  return <Emoji name="cherry-blossom" ref={ref} {...props} />;
});
CherryBlossom.displayName = 'CherryBlossom';

/**
 * Clown Face Emoji Component
 * Category: fun
 */
export const Clown = forwardRef<SVGSVGElement, IndividualEmojiProps>((props, ref) => {
  return <Emoji name="clown" ref={ref} {...props} />;
});
Clown.displayName = 'Clown';

/**
 * Hot Coffee Emoji Component
 * Category: food
 */
export const Coffee = forwardRef<SVGSVGElement, IndividualEmojiProps>((props, ref) => {
  return <Emoji name="coffee" ref={ref} {...props} />;
});
Coffee.displayName = 'Coffee';

/**
 * Confused Emoji Component
 * Category: emotions
 */
export const Confused = forwardRef<SVGSVGElement, IndividualEmojiProps>((props, ref) => {
  return <Emoji name="confused" ref={ref} {...props} />;
});
Confused.displayName = 'Confused';

/**
 * Cool Sunglasses Emoji Component
 * Category: faces
 */
export const Cool = forwardRef<SVGSVGElement, IndividualEmojiProps>((props, ref) => {
  return <Emoji name="cool" ref={ref} {...props} />;
});
Cool.displayName = 'Cool';

/**
 * Crying Waterfall Emoji Component
 * Category: emotions
 */
export const Cry = forwardRef<SVGSVGElement, IndividualEmojiProps>((props, ref) => {
  return <Emoji name="cry" ref={ref} {...props} />;
});
Cry.displayName = 'Cry';

/**
 * Cute Poop Emoji Component
 * Category: fun
 */
export const CutePoop = forwardRef<SVGSVGElement, IndividualEmojiProps>((props, ref) => {
  return <Emoji name="cute-poop" ref={ref} {...props} />;
});
CutePoop.displayName = 'CutePoop';

/**
 * Mischievous Devil Emoji Component
 * Category: faces
 */
export const Devil = forwardRef<SVGSVGElement, IndividualEmojiProps>((props, ref) => {
  return <Emoji name="devil" ref={ref} {...props} />;
});
Devil.displayName = 'Devil';

/**
 * Sparkling Diamond Emoji Component
 * Category: objects
 */
export const Diamond = forwardRef<SVGSVGElement, IndividualEmojiProps>((props, ref) => {
  return <Emoji name="diamond" ref={ref} {...props} />;
});
Diamond.displayName = 'Diamond';

/**
 * Spiral Dizzy Emoji Component
 * Category: reactions
 */
export const Dizzy = forwardRef<SVGSVGElement, IndividualEmojiProps>((props, ref) => {
  return <Emoji name="dizzy" ref={ref} {...props} />;
});
Dizzy.displayName = 'Dizzy';

/**
 * Happy Puppy Emoji Component
 * Category: animals
 */
export const DogPuppy = forwardRef<SVGSVGElement, IndividualEmojiProps>((props, ref) => {
  return <Emoji name="dog-puppy" ref={ref} {...props} />;
});
DogPuppy.displayName = 'DogPuppy';

/**
 * Drooling / Yummy Emoji Component
 * Category: faces
 */
export const Drool = forwardRef<SVGSVGElement, IndividualEmojiProps>((props, ref) => {
  return <Emoji name="drool" ref={ref} {...props} />;
});
Drool.displayName = 'Drool';

/**
 * Rubber Duckling Emoji Component
 * Category: animals
 */
export const Duck = forwardRef<SVGSVGElement, IndividualEmojiProps>((props, ref) => {
  return <Emoji name="duck" ref={ref} {...props} />;
});
Duck.displayName = 'Duck';

/**
 * Starry Excited Emoji Component
 * Category: emotions
 */
export const Excited = forwardRef<SVGSVGElement, IndividualEmojiProps>((props, ref) => {
  return <Emoji name="excited" ref={ref} {...props} />;
});
Excited.displayName = 'Excited';

/**
 * Fingers Crossed Emoji Component
 * Category: gestures
 */
export const FingersCrossed = forwardRef<SVGSVGElement, IndividualEmojiProps>((props, ref) => {
  return <Emoji name="fingers-crossed" ref={ref} {...props} />;
});
FingersCrossed.displayName = 'FingersCrossed';

/**
 * Lit Fire Emoji Component
 * Category: symbols
 */
export const Fire = forwardRef<SVGSVGElement, IndividualEmojiProps>((props, ref) => {
  return <Emoji name="fire" ref={ref} {...props} />;
});
Fire.displayName = 'Fire';

/**
 * Fist Bump Emoji Component
 * Category: gestures
 */
export const FistBump = forwardRef<SVGSVGElement, IndividualEmojiProps>((props, ref) => {
  return <Emoji name="fist-bump" ref={ref} {...props} />;
});
FistBump.displayName = 'FistBump';

/**
 * Frog Sipping Coffee Emoji Component
 * Category: animals
 */
export const FrogCoffee = forwardRef<SVGSVGElement, IndividualEmojiProps>((props, ref) => {
  return <Emoji name="frog-coffee" ref={ref} {...props} />;
});
FrogCoffee.displayName = 'FrogCoffee';

/**
 * Weeping Frog Emoji Component
 * Category: animals
 */
export const FrogCry = forwardRef<SVGSVGElement, IndividualEmojiProps>((props, ref) => {
  return <Emoji name="frog-cry" ref={ref} {...props} />;
});
FrogCry.displayName = 'FrogCry';

/**
 * Dancing Frog Emoji Component
 * Category: animals
 */
export const FrogDance = forwardRef<SVGSVGElement, IndividualEmojiProps>((props, ref) => {
  return <Emoji name="frog-dance" ref={ref} {...props} />;
});
FrogDance.displayName = 'FrogDance';

/**
 * Happy Frog Emoji Component
 * Category: animals
 */
export const FrogHappy = forwardRef<SVGSVGElement, IndividualEmojiProps>((props, ref) => {
  return <Emoji name="frog-happy" ref={ref} {...props} />;
});
FrogHappy.displayName = 'FrogHappy';

/**
 * Frog in Love Emoji Component
 * Category: animals
 */
export const FrogLove = forwardRef<SVGSVGElement, IndividualEmojiProps>((props, ref) => {
  return <Emoji name="frog-love" ref={ref} {...props} />;
});
FrogLove.displayName = 'FrogLove';

/**
 * Friendly Ghost Emoji Component
 * Category: fun
 */
export const Ghost = forwardRef<SVGSVGElement, IndividualEmojiProps>((props, ref) => {
  return <Emoji name="ghost" ref={ref} {...props} />;
});
Ghost.displayName = 'Ghost';

/**
 * Gift Box Emoji Component
 * Category: objects
 */
export const Gift = forwardRef<SVGSVGElement, IndividualEmojiProps>((props, ref) => {
  return <Emoji name="gift" ref={ref} {...props} />;
});
Gift.displayName = 'Gift';

/**
 * Handshake Deal Emoji Component
 * Category: gestures
 */
export const Handshake = forwardRef<SVGSVGElement, IndividualEmojiProps>((props, ref) => {
  return <Emoji name="handshake" ref={ref} {...props} />;
});
Handshake.displayName = 'Handshake';

/**
 * Happy Emoji Component
 * Category: faces
 */
export const Happy = forwardRef<SVGSVGElement, IndividualEmojiProps>((props, ref) => {
  return <Emoji name="happy" ref={ref} {...props} />;
});
Happy.displayName = 'Happy';

/**
 * Heart Hands Emoji Component
 * Category: gestures
 */
export const HeartHands = forwardRef<SVGSVGElement, IndividualEmojiProps>((props, ref) => {
  return <Emoji name="heart-hands" ref={ref} {...props} />;
});
HeartHands.displayName = 'HeartHands';

/**
 * Sparkling Heart Emoji Component
 * Category: love
 */
export const Heart = forwardRef<SVGSVGElement, IndividualEmojiProps>((props, ref) => {
  return <Emoji name="heart" ref={ref} {...props} />;
});
Heart.displayName = 'Heart';

/**
 * 100 Points Emoji Component
 * Category: symbols
 */
export const Hundred = forwardRef<SVGSVGElement, IndividualEmojiProps>((props, ref) => {
  return <Emoji name="hundred" ref={ref} {...props} />;
});
Hundred.displayName = 'Hundred';

/**
 * Soft Serve Ice Cream Emoji Component
 * Category: food
 */
export const IceCream = forwardRef<SVGSVGElement, IndividualEmojiProps>((props, ref) => {
  return <Emoji name="ice-cream" ref={ref} {...props} />;
});
IceCream.displayName = 'IceCream';

/**
 * Laughing Emoji Component
 * Category: faces
 */
export const Laugh = forwardRef<SVGSVGElement, IndividualEmojiProps>((props, ref) => {
  return <Emoji name="laugh" ref={ref} {...props} />;
});
Laugh.displayName = 'Laugh';

/**
 * Heart Eyes Emoji Component
 * Category: love
 */
export const Love = forwardRef<SVGSVGElement, IndividualEmojiProps>((props, ref) => {
  return <Emoji name="love" ref={ref} {...props} />;
});
Love.displayName = 'Love';

/**
 * Mind Blown Emoji Component
 * Category: reactions
 */
export const MindBlown = forwardRef<SVGSVGElement, IndividualEmojiProps>((props, ref) => {
  return <Emoji name="mind-blown" ref={ref} {...props} />;
});
MindBlown.displayName = 'MindBlown';

/**
 * Money Face Emoji Component
 * Category: faces
 */
export const MoneyFace = forwardRef<SVGSVGElement, IndividualEmojiProps>((props, ref) => {
  return <Emoji name="money-face" ref={ref} {...props} />;
});
MoneyFace.displayName = 'MoneyFace';

/**
 * Crescent Moon Emoji Component
 * Category: symbols
 */
export const Moon = forwardRef<SVGSVGElement, IndividualEmojiProps>((props, ref) => {
  return <Emoji name="moon" ref={ref} {...props} />;
});
Moon.displayName = 'Moon';

/**
 * Musical Notes Emoji Component
 * Category: symbols
 */
export const MusicNote = forwardRef<SVGSVGElement, IndividualEmojiProps>((props, ref) => {
  return <Emoji name="music-note" ref={ref} {...props} />;
});
MusicNote.displayName = 'MusicNote';

/**
 * Cute Panda Emoji Component
 * Category: animals
 */
export const Panda = forwardRef<SVGSVGElement, IndividualEmojiProps>((props, ref) => {
  return <Emoji name="panda" ref={ref} {...props} />;
});
Panda.displayName = 'Panda';

/**
 * Party Mascot Emoji Component
 * Category: fun
 */
export const Party = forwardRef<SVGSVGElement, IndividualEmojiProps>((props, ref) => {
  return <Emoji name="party" ref={ref} {...props} />;
});
Party.displayName = 'Party';

/**
 * Peace / Victory Sign Emoji Component
 * Category: gestures
 */
export const Peace = forwardRef<SVGSVGElement, IndividualEmojiProps>((props, ref) => {
  return <Emoji name="peace" ref={ref} {...props} />;
});
Peace.displayName = 'Peace';

/**
 * Cute Piggy Emoji Component
 * Category: animals
 */
export const Piggy = forwardRef<SVGSVGElement, IndividualEmojiProps>((props, ref) => {
  return <Emoji name="piggy" ref={ref} {...props} />;
});
Piggy.displayName = 'Piggy';

/**
 * Pizza Slice Emoji Component
 * Category: food
 */
export const Pizza = forwardRef<SVGSVGElement, IndividualEmojiProps>((props, ref) => {
  return <Emoji name="pizza" ref={ref} {...props} />;
});
Pizza.displayName = 'Pizza';

/**
 * Pleading Puppy Eyes Emoji Component
 * Category: emotions
 */
export const Pleading = forwardRef<SVGSVGElement, IndividualEmojiProps>((props, ref) => {
  return <Emoji name="pleading" ref={ref} {...props} />;
});
Pleading.displayName = 'Pleading';

/**
 * Pointing Right Emoji Component
 * Category: gestures
 */
export const PointingRight = forwardRef<SVGSVGElement, IndividualEmojiProps>((props, ref) => {
  return <Emoji name="pointing-right" ref={ref} {...props} />;
});
PointingRight.displayName = 'PointingRight';

/**
 * Praying / Folded Hands Emoji Component
 * Category: gestures
 */
export const Pray = forwardRef<SVGSVGElement, IndividualEmojiProps>((props, ref) => {
  return <Emoji name="pray" ref={ref} {...props} />;
});
Pray.displayName = 'Pray';

/**
 * Sick / Puking Emoji Component
 * Category: emotions
 */
export const Puke = forwardRef<SVGSVGElement, IndividualEmojiProps>((props, ref) => {
  return <Emoji name="puke" ref={ref} {...props} />;
});
Puke.displayName = 'Puke';

/**
 * Rainbow & Cloud Emoji Component
 * Category: symbols
 */
export const Rainbow = forwardRef<SVGSVGElement, IndividualEmojiProps>((props, ref) => {
  return <Emoji name="rainbow" ref={ref} {...props} />;
});
Rainbow.displayName = 'Rainbow';

/**
 * Ramen Bowl Emoji Component
 * Category: food
 */
export const Ramen = forwardRef<SVGSVGElement, IndividualEmojiProps>((props, ref) => {
  return <Emoji name="ramen" ref={ref} {...props} />;
});
Ramen.displayName = 'Ramen';

/**
 * Launching Rocket Emoji Component
 * Category: objects
 */
export const Rocket = forwardRef<SVGSVGElement, IndividualEmojiProps>((props, ref) => {
  return <Emoji name="rocket" ref={ref} {...props} />;
});
Rocket.displayName = 'Rocket';

/**
 * Rolling Eyes Emoji Component
 * Category: reactions
 */
export const RollingEyes = forwardRef<SVGSVGElement, IndividualEmojiProps>((props, ref) => {
  return <Emoji name="rolling-eyes" ref={ref} {...props} />;
});
RollingEyes.displayName = 'RollingEyes';

/**
 * Sad Pout Emoji Component
 * Category: emotions
 */
export const Sad = forwardRef<SVGSVGElement, IndividualEmojiProps>((props, ref) => {
  return <Emoji name="sad" ref={ref} {...props} />;
});
Sad.displayName = 'Sad';

/**
 * Screaming Shock Emoji Component
 * Category: reactions
 */
export const Scream = forwardRef<SVGSVGElement, IndividualEmojiProps>((props, ref) => {
  return <Emoji name="scream" ref={ref} {...props} />;
});
Scream.displayName = 'Scream';

/**
 * Shy Blush Emoji Component
 * Category: emotions
 */
export const Shy = forwardRef<SVGSVGElement, IndividualEmojiProps>((props, ref) => {
  return <Emoji name="shy" ref={ref} {...props} />;
});
Shy.displayName = 'Shy';

/**
 * Cute Skull Emoji Component
 * Category: symbols
 */
export const Skull = forwardRef<SVGSVGElement, IndividualEmojiProps>((props, ref) => {
  return <Emoji name="skull" ref={ref} {...props} />;
});
Skull.displayName = 'Skull';

/**
 * Sleepy / Zzz Emoji Component
 * Category: faces
 */
export const Sleepy = forwardRef<SVGSVGElement, IndividualEmojiProps>((props, ref) => {
  return <Emoji name="sleepy" ref={ref} {...props} />;
});
Sleepy.displayName = 'Sleepy';

/**
 * Smug / Heh Emoji Component
 * Category: faces
 */
export const Smug = forwardRef<SVGSVGElement, IndividualEmojiProps>((props, ref) => {
  return <Emoji name="smug" ref={ref} {...props} />;
});
Smug.displayName = 'Smug';

/**
 * Magic Sparkles Emoji Component
 * Category: symbols
 */
export const Sparkles = forwardRef<SVGSVGElement, IndividualEmojiProps>((props, ref) => {
  return <Emoji name="sparkles" ref={ref} {...props} />;
});
Sparkles.displayName = 'Sparkles';

/**
 * Golden Star Emoji Component
 * Category: symbols
 */
export const Starry = forwardRef<SVGSVGElement, IndividualEmojiProps>((props, ref) => {
  return <Emoji name="starry" ref={ref} {...props} />;
});
Starry.displayName = 'Starry';

/**
 * Smiling Sun Emoji Component
 * Category: symbols
 */
export const Sun = forwardRef<SVGSVGElement, IndividualEmojiProps>((props, ref) => {
  return <Emoji name="sun" ref={ref} {...props} />;
});
Sun.displayName = 'Sun';

/**
 * Surprised Emoji Component
 * Category: reactions
 */
export const Surprised = forwardRef<SVGSVGElement, IndividualEmojiProps>((props, ref) => {
  return <Emoji name="surprised" ref={ref} {...props} />;
});
Surprised.displayName = 'Surprised';

/**
 * Nervous Sweat Smile Emoji Component
 * Category: faces
 */
export const SweatSmile = forwardRef<SVGSVGElement, IndividualEmojiProps>((props, ref) => {
  return <Emoji name="sweat-smile" ref={ref} {...props} />;
});
SweatSmile.displayName = 'SweatSmile';

/**
 * Thinking Emoji Component
 * Category: emotions
 */
export const Thinking = forwardRef<SVGSVGElement, IndividualEmojiProps>((props, ref) => {
  return <Emoji name="thinking" ref={ref} {...props} />;
});
Thinking.displayName = 'Thinking';

/**
 * Thumbs Down Emoji Component
 * Category: gestures
 */
export const ThumbsDown = forwardRef<SVGSVGElement, IndividualEmojiProps>((props, ref) => {
  return <Emoji name="thumbs-down" ref={ref} {...props} />;
});
ThumbsDown.displayName = 'ThumbsDown';

/**
 * Thumbs Up Emoji Component
 * Category: gestures
 */
export const ThumbsUp = forwardRef<SVGSVGElement, IndividualEmojiProps>((props, ref) => {
  return <Emoji name="thumbs-up" ref={ref} {...props} />;
});
ThumbsUp.displayName = 'ThumbsUp';

/**
 * Waving Hand Emoji Component
 * Category: gestures
 */
export const Wave = forwardRef<SVGSVGElement, IndividualEmojiProps>((props, ref) => {
  return <Emoji name="wave" ref={ref} {...props} />;
});
Wave.displayName = 'Wave';

/**
 * Winking Emoji Component
 * Category: faces
 */
export const Wink = forwardRef<SVGSVGElement, IndividualEmojiProps>((props, ref) => {
  return <Emoji name="wink" ref={ref} {...props} />;
});
Wink.displayName = 'Wink';

/**
 * Yawning / Tired Emoji Component
 * Category: faces
 */
export const Yawn = forwardRef<SVGSVGElement, IndividualEmojiProps>((props, ref) => {
  return <Emoji name="yawn" ref={ref} {...props} />;
});
Yawn.displayName = 'Yawn';

