import * as fs from 'fs';
import * as path from 'path';
import { cleanSvg, extractViewBox } from './optimize-svg';

const ROOT_DIR = process.cwd();
const SVG_DIR = path.join(ROOT_DIR, 'packages', 'assets', 'svg');
const METADATA_FILE = path.join(ROOT_DIR, 'packages', 'assets', 'metadata', 'emojis.json');
const CORE_SRC = path.join(ROOT_DIR, 'packages', 'core', 'src');
const REACT_SRC = path.join(ROOT_DIR, 'packages', 'react', 'src');

function toPascalCase(str: string): string {
  return str
    .split(/[-_]/)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
    .join('');
}

export function generateAll() {
  console.log('✨ Kimo Emoji Library: Starting Code Generation...');

  if (!fs.existsSync(SVG_DIR)) {
    throw new Error(`SVG directory not found at ${SVG_DIR}`);
  }

  const svgFiles = fs.readdirSync(SVG_DIR).filter((f) => f.endsWith('.svg'));
  const metadataRaw = fs.readFileSync(METADATA_FILE, 'utf-8');
  const metadataList = JSON.parse(metadataRaw) as Array<{
    name: string;
    label: string;
    category: string;
    keywords: string[];
    unicode?: string;
    version: string;
  }>;

  const metadataMap = new Map(metadataList.map((m) => [m.name, m]));

  const emojiDataList = svgFiles.map((file) => {
    const name = file.replace(/\.svg$/, '');
    const svgPath = path.join(SVG_DIR, file);
    const rawSvg = fs.readFileSync(svgPath, 'utf-8');
    const cleanedSvg = cleanSvg(rawSvg);
    const viewBox = extractViewBox(rawSvg);

    const meta = metadataMap.get(name) || {
      name,
      label: toPascalCase(name),
      category: 'miscellaneous',
      keywords: [name],
      unicode: '✨',
      version: '1.0.0',
    };

    return {
      name,
      label: meta.label,
      category: meta.category,
      keywords: meta.keywords,
      unicode: meta.unicode || '✨',
      version: meta.version,
      svg: cleanedSvg,
      viewBox,
      componentName: toPascalCase(name),
    };
  });

  // 1. Generate types.ts
  const namesUnion = emojiDataList.map((e) => `  | '${e.name}'`).join('\n');
  const typesContent = `/**
 * Generated by scripts/generate.ts - DO NOT EDIT MANUALLY
 * Source of truth: packages/assets/svg & metadata/emojis.json
 */

export type EmojiName =
${namesUnion};

export type EmojiCategory =
  | 'faces'
  | 'emotions'
  | 'reactions'
  | 'people'
  | 'gestures'
  | 'love'
  | 'fun'
  | 'objects'
  | 'animals'
  | 'food'
  | 'symbols'
  | 'miscellaneous';

export interface EmojiMetadata {
  name: EmojiName;
  label: string;
  category: EmojiCategory;
  keywords: string[];
  unicode?: string;
  version: string;
}

export interface EmojiData extends EmojiMetadata {
  svg: string;
  viewBox: string;
}

export interface SearchOptions {
  category?: EmojiCategory;
  limit?: number;
  exact?: boolean;
}

export interface SvgRenderOptions {
  size?: number | string;
  width?: number | string;
  height?: number | string;
  className?: string;
  ariaLabel?: string;
  ariaHidden?: boolean;
  title?: string;
  style?: Record<string, string | number> | string;
}

export interface CreateEmojiOptions extends SvgRenderOptions {
  onClick?: (event: MouseEvent) => void;
}
`;
  fs.writeFileSync(path.join(CORE_SRC, 'types.ts'), typesContent, 'utf-8');

  // 2. Generate registry.ts
  const registryEntries = emojiDataList
    .map(
      (e) => `  '${e.name}': {
    name: '${e.name}',
    label: ${JSON.stringify(e.label)},
    category: '${e.category}' as EmojiCategory,
    keywords: ${JSON.stringify(e.keywords)},
    unicode: ${JSON.stringify(e.unicode)},
    version: '${e.version}',
    svg: ${JSON.stringify(e.svg)},
    viewBox: '${e.viewBox}',
  },`
    )
    .join('\n');

  const registryContent = `/**
 * Generated by scripts/generate.ts - DO NOT EDIT MANUALLY
 */
import { EmojiData, EmojiName, EmojiCategory } from './types';

export const EMOJI_REGISTRY: Record<EmojiName, EmojiData> = {
${registryEntries}
};

export const EMOJI_LIST: EmojiData[] = Object.values(EMOJI_REGISTRY);

export const EMOJI_NAMES: EmojiName[] = Object.keys(EMOJI_REGISTRY) as EmojiName[];
`;
  fs.writeFileSync(path.join(CORE_SRC, 'registry.ts'), registryContent, 'utf-8');

  // 3. Generate React components in packages/react/src/generated-icons.tsx
  const reactIcons = emojiDataList
    .map((e) => {
      return `/**
 * ${e.label} Emoji Component
 * Category: ${e.category}
 */
export const ${e.componentName} = forwardRef<SVGSVGElement, IndividualEmojiProps>((props, ref) => {
  return <Emoji name="${e.name}" ref={ref} {...props} />;
});
${e.componentName}.displayName = '${e.componentName}';
`;
    })
    .join('\n');

  const reactGeneratedContent = `/**
 * Generated by scripts/generate.ts - DO NOT EDIT MANUALLY
 * Individual tree-shakeable React emoji components
 */
import React, { forwardRef } from 'react';
import { Emoji } from './Emoji';
import { IndividualEmojiProps } from './types';

${reactIcons}
`;
  fs.mkdirSync(path.join(REACT_SRC), { recursive: true });
  fs.writeFileSync(path.join(REACT_SRC, 'generated-icons.tsx'), reactGeneratedContent, 'utf-8');

  console.log(`✅ Successfully generated ${emojiDataList.length} emojis into Core and React packages!`);
}

if (require.main === module || process.argv[1]?.includes('generate')) {
  generateAll();
}
